// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Photos
{
	/// <summary>
	/// RCP method photos.uploadProfilePhoto.
	/// Returns <see cref="Telegram.Api.TL.TLPhotosPhoto"/>
	/// </summary>
	public partial class TLPhotosUploadProfilePhoto : TLObject
	{
		public TLInputFileBase File { get; set; }

		public TLPhotosUploadProfilePhoto() { }
		public TLPhotosUploadProfilePhoto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhotosUploadProfilePhoto; } }

		public override void Read(TLBinaryReader from)
		{
			File = TLFactory.Read<TLInputFileBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4F32C098);
			to.WriteObject(File);
		}
	}
}