// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.getPrivacy
	/// </summary>
	public partial class TLAccountGetPrivacy : TLObject
	{
		public TLInputPrivacyKeyBase Key { get; set; }

		public TLAccountGetPrivacy() { }
		public TLAccountGetPrivacy(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.AccountGetPrivacy; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			Key = TLFactory.Read<TLInputPrivacyKeyBase>(from, cache);
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0xDADBC950);
			to.WriteObject(Key, cache);
			if (cache) WriteToCache(to);
		}
	}
}