import "Composition/DirectRectangleClip.idl";

namespace Telegram.Native.Composition
{
    [default_interface]
    static runtimeclass CompositionDevice 
    {
        static DirectRectangleClip CreateRectangleClip(Microsoft.UI.Xaml.UIElement element);
        [default_overload]
        static DirectRectangleClip CreateRectangleClip(Microsoft.UI.Composition.Visual visual);
        static void SetClip(Microsoft.UI.Composition.Visual visual, DirectRectangleClip clip);
    }
}
