namespace Telegram.Native.Composition
{
    [default_interface]
    runtimeclass DirectRectangleClip
    {
        Single Left;
        Single Top;
        Single Right;
        Single Bottom;

        Single TopLeft;
        Single TopRight;
        Single BottomRight;
        Single BottomLeft;

        void Set(Single uniform);
        void Set(Single topLeft, Single topRight, Single bottomRight, Single bottomLeft);

        void SetInset(Single uniform);
        void SetInset(Single left, Single top, Single right, Single bottom);

        void AnimateTop(Windows.UI.Composition.Compositor compositor, Single from, Single to, Double duration);
        void AnimateBottom(Windows.UI.Composition.Compositor compositor, Single from, Single to, Double duration);
    }
}
