// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Contacts
{
	/// <summary>
	/// RCP method contacts.getBlocked.
	/// Returns <see cref="Telegram.Api.TL.TLContactsBlocked"/>
	/// </summary>
	public partial class TLContactsGetBlocked : TLObject
	{
		public Int32 Offset { get; set; }
		public Int32 Limit { get; set; }

		public TLContactsGetBlocked() { }
		public TLContactsGetBlocked(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsGetBlocked; } }

		public override void Read(TLBinaryReader from)
		{
			Offset = from.ReadInt32();
			Limit = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF57C350F);
			to.Write(Offset);
			to.Write(Limit);
		}
	}
}