// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLAccountPassword : TLAccountPasswordBase 
	{
		public Byte[] CurrentSalt { get; set; }
		public String Hint { get; set; }
		public Boolean HasRecovery { get; set; }

		public TLAccountPassword() { }
		public TLAccountPassword(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.AccountPassword; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			CurrentSalt = from.ReadByteArray();
			NewSalt = from.ReadByteArray();
			Hint = from.ReadString();
			HasRecovery = from.ReadBoolean();
			EmailUnconfirmedPattern = from.ReadString();
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x7C18141C);
			to.WriteByteArray(CurrentSalt);
			to.WriteByteArray(NewSalt);
			to.Write(Hint);
			to.Write(HasRecovery);
			to.Write(EmailUnconfirmedPattern);
			if (cache) WriteToCache(to);
		}
	}
}