// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLAccountPasswordSettings : TLObject 
	{
		public String Email { get; set; }

		public TLAccountPasswordSettings() { }
		public TLAccountPasswordSettings(TLBinaryReader from, TLType type = TLType.AccountPasswordSettings)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.AccountPasswordSettings; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.AccountPasswordSettings)
		{
			Email = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB7B72AB3);
			to.Write(Email);
		}
	}
}