// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLAuthCodeTypeFlashCall : TLAuthCodeTypeBase 
	{
		public TLAuthCodeTypeFlashCall() { }
		public TLAuthCodeTypeFlashCall(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.AuthCodeTypeFlashCall; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x226CCEFB);
			if (cache) WriteToCache(to);
		}
	}
}