// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLChannelParticipantsKicked : TLChannelParticipantsFilterBase 
	{
		public TLChannelParticipantsKicked() { }
		public TLChannelParticipantsKicked(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelParticipantsKicked; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3C37BB7A);
		}
	}
}