// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLChatEmpty : TLChatBase 
	{
		public TLChatEmpty() { }
		public TLChatEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChatEmpty; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9BA2D800);
			to.Write(Id);
		}
	}
}