// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLChannelParticipantsBanned : TLChannelParticipantsFilterBase 
	{
		public String Q { get; set; }

		public TLChannelParticipantsBanned() { }
		public TLChannelParticipantsBanned(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelParticipantsBanned; } }

		public override void Read(TLBinaryReader from)
		{
			Q = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x1427A5E1);
			to.Write(Q);
		}
	}
}