// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLChannelParticipantBanned : TLChannelParticipantBase 
	{
		[Flags]
		public enum Flag : Int32
		{
			Left = (1 << 0),
		}

		public bool IsLeft { get { return Flags.HasFlag(Flag.Left); } set { Flags = value ? (Flags | Flag.Left) : (Flags & ~Flag.Left); } }

		public Flag Flags { get; set; }
		public Int32 KickedBy { get; set; }
		public Int32 Date { get; set; }
		public TLChannelBannedRights BannedRights { get; set; }

		public TLChannelParticipantBanned() { }
		public TLChannelParticipantBanned(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelParticipantBanned; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (Flag)from.ReadInt32();
			UserId = from.ReadInt32();
			KickedBy = from.ReadInt32();
			Date = from.ReadInt32();
			BannedRights = TLFactory.Read<TLChannelBannedRights>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x222C1886);
			to.Write((Int32)Flags);
			to.Write(UserId);
			to.Write(KickedBy);
			to.Write(Date);
			to.WriteObject(BannedRights);
		}
	}
}