// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLChatPhoto : TLChatPhotoBase 
	{
		public TLFileLocationBase PhotoSmall { get; set; }
		public TLFileLocationBase PhotoBig { get; set; }

		public TLChatPhoto() { }
		public TLChatPhoto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChatPhoto; } }

		public override void Read(TLBinaryReader from)
		{
			PhotoSmall = TLFactory.Read<TLFileLocationBase>(from);
			PhotoBig = TLFactory.Read<TLFileLocationBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x6153276A);
			to.WriteObject(PhotoSmall);
			to.WriteObject(PhotoBig);
		}
	}
}