// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public abstract partial class TLChatParticipantBase : TLObject
	{
		public Int32 UserId { get; set; }
		public Int32 InviterId { get; set; }
		public Int32 Date { get; set; }
	}
}