// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLChannelParticipantsKicked : TLChannelParticipantsFilterBase 
	{
		public String Q { get; set; }

		public TLChannelParticipantsKicked() { }
		public TLChannelParticipantsKicked(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelParticipantsKicked; } }

		public override void Read(TLBinaryReader from)
		{
			Q = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xA3B54985);
			to.Write(Q);
		}
	}
}