// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLContactsBlocked : TLContactsBlockedBase 
	{
		public TLContactsBlocked() { }
		public TLContactsBlocked(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsBlocked; } }

		public override void Read(TLBinaryReader from)
		{
			Blocked = TLFactory.Read<TLVector<TLContactBlocked>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x1C138D15);
			to.WriteObject(Blocked);
			to.WriteObject(Users);
		}
	}
}