// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLContactLinkHasPhone : TLContactLinkBase 
	{
		public TLContactLinkHasPhone() { }
		public TLContactLinkHasPhone(TLBinaryReader from, TLType type = TLType.ContactLinkHasPhone)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.ContactLinkHasPhone; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.ContactLinkHasPhone)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x268F3F59);
		}
	}
}