// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLDestroySessionOk : TLDestroySessionResBase 
	{

		public TLDestroySessionOk() { }
		public TLDestroySessionOk(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.DestroySessionOk; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			SessionId = from.ReadInt64();
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0xE22045FC);
			to.Write(SessionId);
			if (cache) WriteToCache(to);
		}
	}
}