// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLDocumentAttributeImageSize : TLDocumentAttributeBase 
	{
		public Int32 W { get; set; }
		public Int32 H { get; set; }

		public TLDocumentAttributeImageSize() { }
		public TLDocumentAttributeImageSize(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.DocumentAttributeImageSize; } }

		public override void Read(TLBinaryReader from)
		{
			W = from.ReadInt32();
			H = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(W);
			to.WriteInt32(H);
		}
	}
}