// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLDocumentAttributeFilename : TLDocumentAttributeBase 
	{
		public String FileName { get; set; }

		public TLDocumentAttributeFilename() { }
		public TLDocumentAttributeFilename(TLBinaryReader from, TLType type = TLType.DocumentAttributeFilename)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.DocumentAttributeFilename; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.DocumentAttributeFilename)
		{
			FileName = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x15590068);
			to.Write(FileName);
		}
	}
}