// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLEncryptedChat : TLEncryptedChatBase 
	{
		public Byte[] GAOrB { get; set; }
		public Int64 KeyFingerprint { get; set; }

		public TLEncryptedChat() { }
		public TLEncryptedChat(TLBinaryReader from, TLType type = TLType.EncryptedChat)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.EncryptedChat; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.EncryptedChat)
		{
			Id = from.ReadInt32();
			AccessHash = from.ReadInt64();
			Date = from.ReadInt32();
			AdminId = from.ReadInt32();
			ParticipantId = from.ReadInt32();
			GAOrB = from.ReadByteArray();
			KeyFingerprint = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xFA56CE36);
			to.Write(Id);
			to.Write(AccessHash);
			to.Write(Date);
			to.Write(AdminId);
			to.Write(ParticipantId);
			to.WriteByteArray(GAOrB);
			to.Write(KeyFingerprint);
		}
	}
}