// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLFutureSalt : TLObject 
	{
		public Int32 ValidSince { get; set; }
		public Int32 ValidUntil { get; set; }
		public Int64 Salt { get; set; }

		public TLFutureSalt() { }
		public TLFutureSalt(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.FutureSalt; } }

		public override void Read(TLBinaryReader from)
		{
			ValidSince = from.ReadInt32();
			ValidUntil = from.ReadInt32();
			Salt = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x0949D9DC);
			to.Write(ValidSince);
			to.Write(ValidUntil);
			to.Write(Salt);
		}
	}
}