// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLHelpInviteText : TLObject 
	{
		public String Message { get; set; }

		public TLHelpInviteText() { }
		public TLHelpInviteText(TLBinaryReader from, TLType type = TLType.HelpInviteText)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.HelpInviteText; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.HelpInviteText)
		{
			Message = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x18CB9F78);
			to.Write(Message);
		}
	}
}