// <auto-generated/>
using System;


namespace Telegram.Api.TL
{
	public partial class TLInputPhoneCall : TLObject 
	{
		public Int64 Id { get; set; }
		public Int64 AccessHash { get; set; }

		public TLInputPhoneCall() { }

		

	}
}