// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLInputEncryptedFileEmpty : TLInputEncryptedFileBase 
	{
		public TLInputEncryptedFileEmpty() { }
		public TLInputEncryptedFileEmpty(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.InputEncryptedFileEmpty; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x1837C364);
			if (cache) WriteToCache(to);
		}
	}
}