// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLInputDocumentEmpty : TLInputDocumentBase 
	{
		public TLInputDocumentEmpty() { }
		public TLInputDocumentEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputDocumentEmpty; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x72F0EAAE);
		}
	}
}