// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLInputMessagesFilterMusic : TLMessagesFilterBase 
	{
		public TLInputMessagesFilterMusic() { }
		public TLInputMessagesFilterMusic(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputMessagesFilterMusic; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
		}
	}
}