// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLInputFileLocation : TLInputFileLocationBase 
	{
		public Int64 VolumeId { get; set; }
		public Int32 LocalId { get; set; }
		public Int64 Secret { get; set; }

		public TLInputFileLocation() { }
		public TLInputFileLocation(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputFileLocation; } }

		public override void Read(TLBinaryReader from)
		{
			VolumeId = from.ReadInt64();
			LocalId = from.ReadInt32();
			Secret = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x14637196);
			to.Write(VolumeId);
			to.Write(LocalId);
			to.Write(Secret);
		}
	}
}