// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLInputPhotoCropAuto : TLInputPhotoCropBase 
	{
		public TLInputPhotoCropAuto() { }
		public TLInputPhotoCropAuto(TLBinaryReader from, TLType type = TLType.InputPhotoCropAuto)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.InputPhotoCropAuto; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.InputPhotoCropAuto)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xADE6B004);
		}
	}
}