// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLInputPrivacyValueAllowAll : TLInputPrivacyRuleBase 
	{
		public TLInputPrivacyValueAllowAll() { }
		public TLInputPrivacyValueAllowAll(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputPrivacyValueAllowAll; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x184B35CE);
		}
	}
}