// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLInputMediaPhotoExternal : TLInputMediaBase, ITLMediaCaption 
	{

		public TLInputMediaPhotoExternal() { }
		public TLInputMediaPhotoExternal(TLBinaryReader from, TLType type = TLType.InputMediaPhotoExternal)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.InputMediaPhotoExternal; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.InputMediaPhotoExternal)
		{
			Url = from.ReadString();
			Caption = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB55F4F18);
			to.Write(Url);
			to.Write(Caption);
		}
	}
}