// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLKeyboardButtonRequestPhone : TLKeyboardButtonBase 
	{

		public TLKeyboardButtonRequestPhone() { }
		public TLKeyboardButtonRequestPhone(TLBinaryReader from, TLType type = TLType.KeyboardButtonRequestPhone)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.KeyboardButtonRequestPhone; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.KeyboardButtonRequestPhone)
		{
			Text = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB16A6C29);
			to.Write(Text);
		}
	}
}