// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLMaskCoords : TLObject 
	{
		public Int32 N { get; set; }
		public Double X { get; set; }
		public Double Y { get; set; }
		public Double Zoom { get; set; }

		public TLMaskCoords() { }
		public TLMaskCoords(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MaskCoords; } }

		public override void Read(TLBinaryReader from)
		{
			N = from.ReadInt32();
			X = from.ReadDouble();
			Y = from.ReadDouble();
			Zoom = from.ReadDouble();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(N);
			to.WriteDouble(X);
			to.WriteDouble(Y);
			to.WriteDouble(Zoom);
		}
	}
}