// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLMessageMediaPhoto : TLMessageMediaBase, ITLMediaCaption 
	{
		public TLPhotoBase Photo { get; set; }
		public String Caption { get; set; }

		public TLMessageMediaPhoto() { }
		public TLMessageMediaPhoto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessageMediaPhoto; } }

		public override void Read(TLBinaryReader from)
		{
			Photo = TLFactory.Read<TLPhotoBase>(from);
			Caption = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3D8CE53D);
			to.WriteObject(Photo);
			to.Write(Caption);
		}
	}
}