// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLMessageActionCustomAction : TLMessageActionBase 
	{
		public String Message { get; set; }

		public TLMessageActionCustomAction() { }
		public TLMessageActionCustomAction(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessageActionCustomAction; } }

		public override void Read(TLBinaryReader from)
		{
			Message = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteString(Message ?? string.Empty);
		}
	}
}