// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLMessagesMessages : TLMessagesMessagesBase 
	{

		public TLMessagesMessages() { }
		public TLMessagesMessages(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.MessagesMessages; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			Messages = TLFactory.Read<TLVector<TLMessageBase>>(from, cache);
			Chats = TLFactory.Read<TLVector<TLChatBase>>(from, cache);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from, cache);
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x8C718E87);
			to.WriteObject(Messages, cache);
			to.WriteObject(Chats, cache);
			to.WriteObject(Users, cache);
			if (cache) WriteToCache(to);
		}
	}
}