// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLMessageMediaPhoto : TLMessageMediaBase 
	{
		[Flags]
		public enum Flag : Int32
		{
			Photo = (1 << 0),
			TTLSeconds = (1 << 2),
		}

		public bool HasPhoto { get { return Flags.HasFlag(Flag.Photo); } set { Flags = value ? (Flags | Flag.Photo) : (Flags & ~Flag.Photo); } }
		public bool HasTTLSeconds { get { return Flags.HasFlag(Flag.TTLSeconds); } set { Flags = value ? (Flags | Flag.TTLSeconds) : (Flags & ~Flag.TTLSeconds); } }

		public Flag Flags { get; set; }
		public TLPhotoBase Photo { get; set; }
		public Int32? TTLSeconds { get; set; }

		public TLMessageMediaPhoto() { }
		public TLMessageMediaPhoto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessageMediaPhoto; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (Flag)from.ReadInt32();
			if (HasPhoto) Photo = TLFactory.Read<TLPhotoBase>(from);
			if (HasTTLSeconds) TTLSeconds = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			UpdateFlags();

			to.WriteInt32((Int32)Flags);
			if (HasPhoto) to.WriteObject(Photo);
			if (HasTTLSeconds) to.WriteInt32(TTLSeconds.Value);
		}

		private void UpdateFlags()
		{
			HasPhoto = Photo != null;
			HasTTLSeconds = TTLSeconds != null;
		}
	}
}