// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLMessagesDHConfig : TLMessagesDHConfigBase 
	{
		public Int32 G { get; set; }
		public Byte[] P { get; set; }
		public Int32 Version { get; set; }

		public TLMessagesDHConfig() { }
		public TLMessagesDHConfig(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.MessagesDHConfig; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			G = from.ReadInt32();
			P = from.ReadByteArray();
			Version = from.ReadInt32();
			Random = from.ReadByteArray();
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x2C221EDD);
			to.Write(G);
			to.WriteByteArray(P);
			to.Write(Version);
			to.WriteByteArray(Random);
			if (cache) WriteToCache(to);
		}
	}
}