// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLMessagesFeaturedStickersNotModified : TLMessagesFeaturedStickersBase 
	{
		public TLMessagesFeaturedStickersNotModified() { }
		public TLMessagesFeaturedStickersNotModified(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesFeaturedStickersNotModified; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4EDE3CF);
		}
	}
}