// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLPhotosPhotosSlice : TLPhotosPhotosBase 
	{
		public Int32 Count { get; set; }

		public TLPhotosPhotosSlice() { }
		public TLPhotosPhotosSlice(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhotosPhotosSlice; } }

		public override void Read(TLBinaryReader from)
		{
			Count = from.ReadInt32();
			Photos = TLFactory.Read<TLVector<TLPhotoBase>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x15051F54);
			to.Write(Count);
			to.WriteObject(Photos);
			to.WriteObject(Users);
		}
	}
}