// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public abstract partial class TLPhotosPhotosBase : TLObject
	{
		public TLVector<TLPhotoBase> Photos { get; set; }
		public TLVector<TLUserBase> Users { get; set; }
	}
}