// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLRPCAnswerDropped : TLRPCDropAnswerBase 
	{
		public Int64 MsgId { get; set; }
		public Int32 SeqNo { get; set; }
		public Int32 Bytes { get; set; }

		public TLRPCAnswerDropped() { }
		public TLRPCAnswerDropped(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.RPCAnswerDropped; } }

		public override void Read(TLBinaryReader from)
		{
			MsgId = from.ReadInt64();
			SeqNo = from.ReadInt32();
			Bytes = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xA43AD8B7);
			to.Write(MsgId);
			to.Write(SeqNo);
			to.Write(Bytes);
		}
	}
}