// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLSendMessageUploadVideoAction : TLSendMessageActionBase 
	{
		public Int32 Progress { get; set; }

		public TLSendMessageUploadVideoAction() { }
		public TLSendMessageUploadVideoAction(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.SendMessageUploadVideoAction; } }

		public override void Read(TLBinaryReader from)
		{
			Progress = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE9763AEC);
			to.Write(Progress);
		}
	}
}