// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLServerDHParamsFail : TLServerDHParamsBase 
	{
		public TLInt128 NewNonceHash { get; set; }

		public TLServerDHParamsFail() { }
		public TLServerDHParamsFail(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.ServerDHParamsFail; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			Nonce = new TLInt128(from, cache);
			ServerNonce = new TLInt128(from, cache);
			NewNonceHash = new TLInt128(from, cache);
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x79CB045D);
			to.WriteObject(Nonce, cache);
			to.WriteObject(ServerNonce, cache);
			to.WriteObject(NewNonceHash, cache);
			if (cache) WriteToCache(to);
		}
	}
}