// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLSendMessageUploadDocumentAction : TLSendMessageActionBase 
	{
		public Int32 Progress { get; set; }

		public TLSendMessageUploadDocumentAction() { }
		public TLSendMessageUploadDocumentAction(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.SendMessageUploadDocumentAction; } }

		public override void Read(TLBinaryReader from)
		{
			Progress = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xAA0CD9E4);
			to.Write(Progress);
		}
	}
}