// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLServerDHParamsFail : TLServerDHParamsBase 
	{
		public TLInt128 NewNonceHash { get; set; }

		public TLServerDHParamsFail() { }
		public TLServerDHParamsFail(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ServerDHParamsFail; } }

		public override void Read(TLBinaryReader from)
		{
			Nonce = new TLInt128(from);
			ServerNonce = new TLInt128(from);
			NewNonceHash = new TLInt128(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x79CB045D);
			to.WriteObject(Nonce);
			to.WriteObject(ServerNonce);
			to.WriteObject(NewNonceHash);
		}
	}
}