// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLServerDHParamsOk : TLServerDHParamsBase 
	{
		public Byte[] EncryptedAnswer { get; set; }

		public TLServerDHParamsOk() { }
		public TLServerDHParamsOk(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ServerDHParamsOk; } }

		public override void Read(TLBinaryReader from)
		{
			Nonce = new TLInt128(from);
			ServerNonce = new TLInt128(from);
			EncryptedAnswer = from.ReadByteArray();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xD0E8075C);
			to.WriteObject(Nonce);
			to.WriteObject(ServerNonce);
			to.WriteByteArray(EncryptedAnswer);
		}
	}
}