// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLTextPlain : TLRichTextBase 
	{
		public String Text { get; set; }

		public TLTextPlain() { }
		public TLTextPlain(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.TextPlain; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			Text = from.ReadString();
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x744694E0);
			to.Write(Text);
			if (cache) WriteToCache(to);
		}
	}
}