// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLTopPeerCategoryBotsPM : TLTopPeerCategoryBase 
	{
		public TLTopPeerCategoryBotsPM() { }
		public TLTopPeerCategoryBotsPM(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.TopPeerCategoryBotsPM; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
		}
	}
}