// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLUpdateEncryptedChatTyping : TLUpdateBase 
	{
		public Int32 ChatId { get; set; }

		public TLUpdateEncryptedChatTyping() { }
		public TLUpdateEncryptedChatTyping(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateEncryptedChatTyping; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(ChatId);
		}
	}
}