// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLUpdatesDifferenceEmpty : TLUpdatesDifferenceBase 
	{
		public Int32 Date { get; set; }
		public Int32 Seq { get; set; }

		public TLUpdatesDifferenceEmpty() { }
		public TLUpdatesDifferenceEmpty(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.UpdatesDifferenceEmpty; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			Date = from.ReadInt32();
			Seq = from.ReadInt32();
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x5D75A138);
			to.Write(Date);
			to.Write(Seq);
			if (cache) WriteToCache(to);
		}
	}
}