// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLUpdatePhoneCall : TLUpdateBase 
	{
		public TLPhoneCallBase PhoneCall { get; set; }

		public TLUpdatePhoneCall() { }
		public TLUpdatePhoneCall(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.UpdatePhoneCall; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			PhoneCall = TLFactory.Read<TLPhoneCallBase>(from, cache);
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0xAB0F6B1E);
			to.WriteObject(PhoneCall, cache);
			if (cache) WriteToCache(to);
		}
	}
}