// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLUpdateChatParticipantAdd : TLUpdateBase 
	{
		public Int32 ChatId { get; set; }
		public Int32 UserId { get; set; }
		public Int32 InviterId { get; set; }
		public Int32 Date { get; set; }
		public Int32 Version { get; set; }

		public TLUpdateChatParticipantAdd() { }
		public TLUpdateChatParticipantAdd(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.UpdateChatParticipantAdd; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			ChatId = from.ReadInt32();
			UserId = from.ReadInt32();
			InviterId = from.ReadInt32();
			Date = from.ReadInt32();
			Version = from.ReadInt32();
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0xEA4B0E5C);
			to.Write(ChatId);
			to.Write(UserId);
			to.Write(InviterId);
			to.Write(Date);
			to.Write(Version);
			if (cache) WriteToCache(to);
		}
	}
}