// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLUpdateChatParticipantAdmin : TLUpdateBase 
	{
		public Int32 ChatId { get; set; }
		public Int32 UserId { get; set; }
		public Boolean IsAdmin { get; set; }
		public Int32 Version { get; set; }

		public TLUpdateChatParticipantAdmin() { }
		public TLUpdateChatParticipantAdmin(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateChatParticipantAdmin; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
			UserId = from.ReadInt32();
			IsAdmin = from.ReadBoolean();
			Version = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(ChatId);
			to.WriteInt32(UserId);
			to.WriteBoolean(IsAdmin);
			to.WriteInt32(Version);
		}
	}
}