// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLUpdateShort : TLUpdatesBase 
	{
		public TLUpdateBase Update { get; set; }

		public TLUpdateShort() { }
		public TLUpdateShort(TLBinaryReader from, TLType type = TLType.UpdateShort)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.UpdateShort; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.UpdateShort)
		{
			Update = TLFactory.Read<TLUpdateBase>(from);
			Date = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x78D4DEC1);
			to.WriteObject(Update);
			to.Write(Date);
		}
	}
}