// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLUpdateChannel : TLUpdateBase 
	{
		public Int32 ChannelId { get; set; }

		public TLUpdateChannel() { }
		public TLUpdateChannel(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateChannel; } }

		public override void Read(TLBinaryReader from)
		{
			ChannelId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(ChannelId);
		}
	}
}