// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLUpdatesTooLong : TLUpdatesBase 
	{
		public TLUpdatesTooLong() { }
		public TLUpdatesTooLong(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdatesTooLong; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE317AF7E);
		}
	}
}