// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLUserStatusRecently : TLUserStatusBase 
	{
		public TLUserStatusRecently() { }
		public TLUserStatusRecently(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UserStatusRecently; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE26F42F1);
		}
	}
}