// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLUserStatusLastMonth : TLUserStatusBase 
	{
		public TLUserStatusLastMonth() { }
		public TLUserStatusLastMonth(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.UserStatusLastMonth; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x77EBC742);
			if (cache) WriteToCache(to);
		}
	}
}