// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLWebPageEmpty : TLWebPageBase 
	{
		public Int64 Id { get; set; }

		public TLWebPageEmpty() { }
		public TLWebPageEmpty(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.WebPageEmpty; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			Id = from.ReadInt64();
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0xEB1477E8);
			to.Write(Id);
			if (cache) WriteToCache(to);
		}
	}
}