// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL.Messages.Methods
{
	/// <summary>
	/// RCP method messages.discardEncryption.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
	public partial class TLMessagesDiscardEncryption : TLObject
	{
		public Int32 ChatId { get; set; }

		public TLMessagesDiscardEncryption() { }
		public TLMessagesDiscardEncryption(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesDiscardEncryption; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(ChatId);
		}
	}
}