// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL.Help.Methods
{
	/// <summary>
	/// RCP method help.getAppUpdate.
	/// Returns <see cref="Telegram.Api.TL.TLHelpAppUpdate"/>
	/// </summary>
	public partial class TLHelpGetAppUpdate : TLObject
	{
		public TLHelpGetAppUpdate() { }
		public TLHelpGetAppUpdate(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpGetAppUpdate; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
		}
	}
}