import "VideoAnimation.idl";

namespace Unigram.Native
{
    [default_interface]
    runtimeclass CachedVideoAnimation : Windows.Foundation.IClosable
    {
		static CachedVideoAnimation LoadFromFile(IVideoAnimationSource file, Boolean precache);

        void RenderSync(Microsoft.Graphics.Canvas.CanvasBitmap bitmap, out Int32 seconds);
        void Stop();

        Double FrameRate{ get; };
        Int32 TotalFrame{ get; };
        Windows.Foundation.Size Size{ get; };
        Boolean IsCaching{ get; };

        Int32 PixelWidth{ get; };
        Int32 PixelHeight{ get; };
    }
}
