namespace Unigram.Native
{
	[default_interface]
	runtimeclass PlaceholderImageHelper
	{
		static PlaceholderImageHelper Current{ get; };

		void WriteBytes(Windows.Foundation.Collections.IVector<byte> hash, Windows.Storage.Streams.IRandomAccessStream randomAccessStream);

		void DrawWebP(String fileName, Int32 maxWidth, Windows.Storage.Streams.IRandomAccessStream randomAccessStream, out Windows.Foundation.Size size);

		void DrawSvg(String path, Windows.UI.Color foreground, Windows.Storage.Streams.IRandomAccessStream randomAccessStream, out Windows.Foundation.Size size);
		void DrawQr(String data, Windows.UI.Color foreground, Windows.UI.Color background, Windows.Storage.Streams.IRandomAccessStream randomAccessStream);
		void DrawIdenticon(Windows.Foundation.Collections.IVector<byte> hash, Int32 side, Windows.Storage.Streams.IRandomAccessStream randomAccessStream);

		void DrawGlyph(String glyph, Windows.UI.Color top, Windows.UI.Color bottom, Windows.Storage.Streams.IRandomAccessStream randomAccessStream);
		void DrawSavedMessages(Windows.UI.Color top, Windows.UI.Color bottom, Windows.Storage.Streams.IRandomAccessStream randomAccessStream);
		void DrawDeletedUser(Windows.UI.Color top, Windows.UI.Color bottom, Windows.Storage.Streams.IRandomAccessStream randomAccessStream);
		void DrawProfilePlaceholder(String text, Windows.UI.Color top, Windows.UI.Color bottom, Windows.Storage.Streams.IRandomAccessStream randomAccessStream);

		[default_overload]
		void DrawThumbnailPlaceholder(String fileName, Single blurAmount, Windows.Storage.Streams.IRandomAccessStream randomAccessStream);
		void DrawThumbnailPlaceholder(Windows.Foundation.Collections.IVector<byte> bytes, Single blurAmount, Windows.Storage.Streams.IRandomAccessStream randomAccessStream);
	}
} // namespace Unigram.Native
