namespace Unigram.Native
{
    [default_interface]
    runtimeclass ScreenshotManager
    {
        static Windows.UI.Xaml.Media.ImageSource Capture();

        static Windows.Foundation.Rect GetWorkingArea();
    }
}
