namespace Telegram.Native
{
    delegate void TelegramWebviewProxyDelegate(String eventName, String eventData);

    [allowforweb]
    [default_interface]
    runtimeclass TelegramWebviewProxy
    {
        TelegramWebviewProxy(TelegramWebviewProxyDelegate delegato);

        void PostEvent(String eventName, String eventData);
    }
} // namespace Telegram.Native
