namespace Unigram.Native
{
    delegate void TelegramPaymentProxyDelegate(String title, String credentials);

    [allowforweb]
    [default_interface]
    runtimeclass TelegramPaymentProxy
    {
        TelegramPaymentProxy(TelegramPaymentProxyDelegate delegato);

        void PostEvent(String eventName, String eventData);
    }
} // namespace Unigram.Native
