namespace Unigram.Native
{
	interface IVideoAnimationSource {
		void SeekCallback(Int64 offset);
		void ReadCallback(Int64 count);

		String FilePath{ get; };
		Int64 FileSize{ get; };

		Int64 Offset{ get; };

		Int32 Id{ get; };
	};

	[default_interface]
	runtimeclass VideoAnimation : Windows.Foundation.IClosable
	{
		static VideoAnimation LoadFromFile(IVideoAnimationSource file, Boolean preview, Boolean limitFps);

		void Stop();
		void PrepareToSeek();
		void SeekToMilliseconds(Int64 ms, Boolean precise);

		Int32 RenderSync(Microsoft.Graphics.Canvas.CanvasBitmap bitmap, Boolean preview, out Int32 seconds);

		Int32 PixelWidth{ get; };
		Int32 PixelHeight{ get; };

		Double FrameRate{ get; };
	}
} // namespace Unigram.Native
