// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL.Messages
{
	public partial class TLMessagesStickerSetInstallResultArchive : TLMessagesStickerSetInstallResultBase 
	{
		public TLVector<TLStickerSetCoveredBase> Sets { get; set; }

		public TLMessagesStickerSetInstallResultArchive() { }
		public TLMessagesStickerSetInstallResultArchive(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesStickerSetInstallResultArchive; } }

		public override void Read(TLBinaryReader from)
		{
			Sets = TLFactory.Read<TLVector<TLStickerSetCoveredBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteObject(Sets);
		}
	}
}