namespace Telegram.Native.Controls
{
    [default_interface]
    runtimeclass AutomaticDragHelper 
    {
        AutomaticDragHelper(Windows.UI.Xaml.UIElement pUIElement, Boolean shouldAddInputHandlers);

        void StartDetectingDrag();
        void StopDetectingDrag();
    }
}
