namespace Telegram.Native.Controls
{
    [default_interface]
    unsealed runtimeclass ControlEx : Windows.UI.Xaml.Controls.Control
    {
        ControlEx();

        Boolean IsConnected{ get; };
        Boolean IsDisconnected{ get; };

        overridable void OnLoaded();
        overridable void OnUnloaded();
    }

    [default_interface]
    unsealed runtimeclass GridEx : Windows.UI.Xaml.Controls.Grid
    {
        GridEx();

        Boolean IsConnected{ get; };
        Boolean IsDisconnected{ get; };

        overridable void OnLoaded();
        overridable void OnUnloaded();
    }

    [default_interface]
    unsealed runtimeclass HyperlinkButtonEx : Windows.UI.Xaml.Controls.HyperlinkButton
    {
        HyperlinkButtonEx();

        Boolean IsConnected{ get; };
        Boolean IsDisconnected{ get; };

        overridable void OnLoaded();
        overridable void OnUnloaded();
    }

    [default_interface]
    unsealed runtimeclass ToggleButtonEx : Windows.UI.Xaml.Controls.Primitives.ToggleButton
    {
        ToggleButtonEx();

        Boolean IsConnected{ get; };
        Boolean IsDisconnected{ get; };

        overridable void OnLoaded();
        overridable void OnUnloaded();
    }
}
