// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Bots
{
	/// <summary>
	/// RCP method bots.answerWebhookJSONQuery.
	/// Returns <see cref="Telegram.Api.TL.TLBoolBase"/>
	/// </summary>
	public partial class TLBotsAnswerWebhookJSONQuery : TLObject
	{
		public Int64 QueryId { get; set; }
		public TLDataJSON Data { get; set; }

		public TLBotsAnswerWebhookJSONQuery() { }
		public TLBotsAnswerWebhookJSONQuery(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.BotsAnswerWebhookJSONQuery; } }

		public override void Read(TLBinaryReader from)
		{
			QueryId = from.ReadInt64();
			Data = TLFactory.Read<TLDataJSON>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE6213F4D);
			to.Write(QueryId);
			to.WriteObject(Data);
		}
	}
}