// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Contest
{
	/// <summary>
	/// RCP method contest.saveDeveloperInfo
	/// </summary>
	public partial class TLContestSaveDeveloperInfo : TLObject
	{
		public Int32 VkId { get; set; }
		public String Name { get; set; }
		public String PhoneNumber { get; set; }
		public Int32 Age { get; set; }
		public String City { get; set; }

		public TLContestSaveDeveloperInfo() { }
		public TLContestSaveDeveloperInfo(TLBinaryReader from, bool cache = false)
		{
			Read(from, cache);
		}

		public override TLType TypeId { get { return TLType.ContestSaveDeveloperInfo; } }

		public override void Read(TLBinaryReader from, bool cache = false)
		{
			VkId = from.ReadInt32();
			Name = from.ReadString();
			PhoneNumber = from.ReadString();
			Age = from.ReadInt32();
			City = from.ReadString();
			if (cache) ReadFromCache(from);
		}

		public override void Write(TLBinaryWriter to, bool cache = false)
		{
			to.Write(0x9A5F6E95);
			to.Write(VkId);
			to.Write(Name);
			to.Write(PhoneNumber);
			to.Write(Age);
			to.Write(City);
			if (cache) WriteToCache(to);
		}
	}
}