namespace Telegram.Native
{
    enum AnimationEffectsState
    {
        Auto = -1,
        Disabled = 0,
        Enabled = 1
    };

    [default_interface]
    runtimeclass AnimationEffects 
    {
        static Boolean Supported{ get; };
        static Boolean Enabled{ get; };

        static void Initialize();

        static AnimationEffectsState State;
    }
}
