import "VideoAnimation.idl";

namespace Telegram.Native
{
    [default_interface]
    runtimeclass CachedVideoAnimation : Windows.Foundation.IClosable
    {
		static CachedVideoAnimation LoadFromFile(IVideoAnimationSource file, Int32 width, Int32 height, Boolean precache);

        void RenderSync(Windows.Storage.Streams.IBuffer bitmap, Int32 width, Int32 height, out Int32 seconds, out Boolean completed);
        void Stop();
        void Cache(Int32 width, Int32 height);

        Double FrameRate{ get; };
        Int32 TotalFrame{ get; };
        Boolean IsCaching{ get; };
        Boolean IsReadyToCache{ get; };

        Int32 PixelWidth{ get; };
        Int32 PixelHeight{ get; };
    }
}
