import "FatalError.idl";

namespace Telegram.Native
{
    delegate void FatalErrorCallback(FatalError error);

    enum TextDirectionality
    {
        Neutral,
        LeftToRight,
        RightToLeft
    };

    [default_interface]
    runtimeclass NativeUtils
    {
        static Boolean FileExists(String path);

        static Int64 GetDirectorySize(String path);
        static Int64 GetDirectorySize(String path, String filter);
        static void CleanDirectory(String path, Int32 days);
        static void Delete(String path);

        static Int32 GetLastInputTime();

        //[DefaultOverload]
        static TextDirectionality GetDirectionality(String value);
        static TextDirectionality GetDirectionality(String value, Int32 offset);
        static TextDirectionality GetDirectionality(String value, Int32 offset, Int32 length);
        //static Int32 GetDirectionality(char16 value);

        static String GetCurrentCulture();
        static String GetKeyboardCulture();

        [default_overload]
        static String FormatTime(Int32 value);
        static String FormatTime(Windows.Foundation.DateTime value);

        [default_overload]
        static String FormatDate(Int32 value, String format);
        static String FormatDate(Windows.Foundation.DateTime value, String format);
        static String FormatDate(Int32 year, Int32 month, Int32 day, String format);

        [default_overload]
        static Boolean IsFileReadable(String path);
        static Boolean IsFileReadable(String path, out Int64 fileSize, out Int64 fileTime);

        static Boolean IsMediaSupported();

        static void OverrideScaleForCurrentView(Int32 value);
        static Int32 GetScaleForCurrentView();

        static void SetFatalErrorCallback(FatalErrorCallback action);
        static FatalError GetFatalError(Boolean onlyNative);
        static FatalError GetBackTrace(UInt64 code);

        static void Crash();
    }
} // namespace Telegram.Native
