namespace Telegram.Native
{
    delegate void FatalErrorCallback(String stackTrace);

    enum NativeDirectionality
    {
        Neutral,
        LeftToRight,
        RightToLeft
    };

    [default_interface]
    runtimeclass NativeUtils
    {
        static Boolean FileExists(String path);

        static Int64 GetDirectorySize(String path);
        static Int64 GetDirectorySize(String path, String filter);
        static void CleanDirectory(String path, Int32 days);
        static void Delete(String path);

        static Int32 GetLastInputTime();

        //[DefaultOverload]
        static NativeDirectionality GetDirectionality(String value);
        //static Int32 GetDirectionality(char16 value);

        static String GetCurrentCulture();

        static String GetKeyboardCulture();

        [default_overload]
        static Boolean IsFileReadable(String path);
        static Boolean IsFileReadable(String path, out Int64 fileSize, out Int64 fileTime);

        static Boolean IsMediaSupported();

        static void SetFatalErrorCallback(FatalErrorCallback action);

        static String GetBacktrace();
        static void Crash();
    }
} // namespace Telegram.Native
