namespace Telegram.Native.Media
{
    [default_interface]
    runtimeclass AsyncMediaPlayerDurationChangedEventArgs 
    {
        AsyncMediaPlayerDurationChangedEventArgs(Double duration);
        Double Duration;
    }
}
