import "Media/AsyncMediaPlayerSwapChain.idl";

namespace Telegram.Native.Media
{
    [flags]
    enum AsyncMediaPlayerMode
    {
        None,
        Audio,
        Video
    };

    [default_interface]
    runtimeclass AsyncMediaPlayerOptions
    {
        AsyncMediaPlayerOptions();
        AsyncMediaPlayerMode Mode;
        Boolean Debug;
        Boolean CreateSwapChain;
        Boolean Mute;
        Double Volume;
        Double Rate;
        Windows.Foundation.Collections.IVector<String> Arguments{ get; };
    }
}
