namespace Telegram.Native.Media
{
    enum AsyncMediaPlayerState
    {
        NothingSpecial = 0,
        Opening = 1,
        Buffering = 2,
        Playing = 3,
        Paused = 4,
        Stopped = 5,
        Ended = 6,
        Error = 7
    };

    [default_interface]
    runtimeclass AsyncMediaPlayerStateChangedEventArgs 
    {
        AsyncMediaPlayerStateChangedEventArgs(AsyncMediaPlayerState state);
        AsyncMediaPlayerState State;
    }
}
