namespace Telegram.Native.Media
{
    [default_interface]
    runtimeclass AsyncMediaPlayerBufferingEventArgs 
    {
        AsyncMediaPlayerBufferingEventArgs(Single cache);
        Single Cache;
    }
}
