// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods
{
	/// <summary>
	/// RCP method invokeAfterMsg.
	/// Returns <see cref="Telegram.Api.TL.TLObject"/>
	/// </summary>
	public partial class TLInvokeAfterMsg : TLObject
	{
		public Int64 MsgId { get; set; }
		public TLObject Query { get; set; }

		public TLInvokeAfterMsg() { }
		public TLInvokeAfterMsg(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InvokeAfterMsg; } }

		public override void Read(TLBinaryReader from)
		{
			MsgId = from.ReadInt64();
			Query = TLFactory.Read<TLObject>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xCB9F372D);
			to.Write(MsgId);
			to.WriteObject(Query);
		}
	}
}