namespace Telegram.Native.Calls
{
    [default_interface]
    runtimeclass VoipVideoRendererToken
    {
        Int32 AudioSource{ get; };
        String EndpointId{ get; };
        IVector<Telegram.Td.Api.GroupCallVideoSourceGroup> SourceGroups{ get; };

        Windows.UI.Xaml.Media.Stretch Stretch;
        Boolean IsMirrored;

        Boolean IsMatch(String endpointId, Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl canvasControl);

        void Stop();
    }
}
