import "VoipVideoRendererToken.idl";

namespace Telegram.Native.Calls
{
    enum VoipVideoChannelQuality {
        Thumbnail = 0,
        Medium = 1,
        Full = 2
    };

    [default_interface]
    runtimeclass VoipVideoChannelInfo
    {
        VoipVideoChannelInfo();
        VoipVideoChannelInfo(Int32 audioSource, String endpointId, IVector<Telegram.Td.Api.GroupCallVideoSourceGroup> sourceGroups, VoipVideoChannelQuality minQuality, VoipVideoChannelQuality maxQuality);
        VoipVideoChannelInfo(VoipVideoRendererToken token, VoipVideoChannelQuality minQuality, VoipVideoChannelQuality maxQuality);

        Int32 AudioSource;
        String EndpointId;
        IVector<Telegram.Td.Api.GroupCallVideoSourceGroup> SourceGroups;
        VoipVideoChannelQuality MinQuality;
        VoipVideoChannelQuality MaxQuality;
    }
}
