namespace Telegram.Native.Calls
{
    enum VoipVideoChannelQuality
    {
        Thumbnail = 0,
        Medium = 1,
        Full = 2
    };

    [default_interface]
    runtimeclass VoipVideoChannelInfo
    {
        VoipVideoChannelInfo(Int32 audioSource, String endpointId, IVector<Telegram.Td.Api.GroupCallVideoSourceGroup> sourceGroups, VoipVideoChannelQuality minQuality, VoipVideoChannelQuality maxQuality);

        Int32 AudioSource{ get; };
        String EndpointId{ get; };
        IVector<Telegram.Td.Api.GroupCallVideoSourceGroup> SourceGroups{ get; };
        VoipVideoChannelQuality MinQuality{ get; };
        VoipVideoChannelQuality MaxQuality{ get; };
    }
}
