namespace Telegram.Native.Calls
{
    [default_interface]
    runtimeclass VoipVideoSourceGroup 
    {
        VoipVideoSourceGroup(String semantics, IVectorView<Int32> sourceIds);

        String Semantics;
        IVectorView<Int32> SourceIds;
    }
}
