namespace Telegram.Native.Calls
{
    [default_interface]
    runtimeclass VoipVideoRendererToken
    {
        Windows.UI.Xaml.Media.Stretch Stretch;
        Boolean IsMirrored;

        Boolean Matches(String endpointId, Guid visualId);

        void Stop();
    }
}
