// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL.Payments
{
	public partial class TLPaymentsPaymentVerficationNeeded : TLPaymentsPaymentResultBase 
	{
		public String Url { get; set; }

		public TLPaymentsPaymentVerficationNeeded() { }
		public TLPaymentsPaymentVerficationNeeded(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PaymentsPaymentVerficationNeeded; } }

		public override void Read(TLBinaryReader from)
		{
			Url = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteString(Url ?? string.Empty);
		}
	}
}