using System.Collections.Generic;
using Unigram.Common;
using Unigram.Services.Settings;
using Windows.UI;

namespace Unigram.Services
{
    public partial class ThemeInfoBase
    {
        public static Dictionary<TelegramThemeType, Dictionary<AccentShade, Color>> Accents => _accent;

        protected static readonly Dictionary<TelegramThemeType, Dictionary<AccentShade, Color>> _accent = new Dictionary<TelegramThemeType, Dictionary<AccentShade, Color>>
        {
            {
                TelegramThemeType.Tinted, new Dictionary<AccentShade, Color>
                {
                    { AccentShade.Default, ColorEx.FromHex(0xFF5288C1) },
                    { AccentShade.Light1, ColorEx.FromHex(0xFF5894d4) },
                    { AccentShade.Light2, ColorEx.FromHex(0xFF72a1d3) },
                    { AccentShade.Light3, ColorEx.FromHex(0xFF9ab4cf) },
                    { AccentShade.Dark1, ColorEx.FromHex(0xFF417bb7) },
                    { AccentShade.Dark2, ColorEx.FromHex(0xFF3c6ea3) },
                    { AccentShade.Dark3, ColorEx.FromHex(0xFF355d86) },
                }
            },
            {
                TelegramThemeType.Night, new Dictionary<AccentShade, Color>
                {
                    { AccentShade.Default, ColorEx.FromHex(0xFF5288C1) },
                    { AccentShade.Light1, ColorEx.FromHex(0xFF5894d4) },
                    { AccentShade.Light2, ColorEx.FromHex(0xFF72a1d3) },
                    { AccentShade.Light3, ColorEx.FromHex(0xFF9ab4cf) },
                    { AccentShade.Dark1, ColorEx.FromHex(0xFF417bb7) },
                    { AccentShade.Dark2, ColorEx.FromHex(0xFF3c6ea3) },
                    { AccentShade.Dark3, ColorEx.FromHex(0xFF355d86) },
                }
            },
            {
                TelegramThemeType.Day, new Dictionary<AccentShade, Color>
                {
                    { AccentShade.Default, ColorEx.FromHex(0xFF40A7E3) },
                    { AccentShade.Light1, ColorEx.FromHex(0xFF4db3ee) },
                    { AccentShade.Light2, ColorEx.FromHex(0xFF6fbae6) },
                    { AccentShade.Light3, ColorEx.FromHex(0xFF98c6e1) },
                    { AccentShade.Dark1, ColorEx.FromHex(0xFF299cdf) },
                    { AccentShade.Dark2, ColorEx.FromHex(0xFF1e8fd1) },
                    { AccentShade.Dark3, ColorEx.FromHex(0xFF2178aa) },
                }
            }
        };

        protected static readonly Dictionary<TelegramThemeType, Dictionary<string, Color>> _map = new Dictionary<TelegramThemeType, Dictionary<string, Color>>
        {
            {
                TelegramThemeType.Tinted, new Dictionary<string, Color>
                {
                    { "PageTitleBackgroundBrush", ColorEx.FromHex(0xFF151D26) },
                    { "PinnedMessageForegroundBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "PageHeaderHighlightBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "PageBackgroundDarkBrush", ColorEx.FromHex(0xFF151D26) },
                    { "PinnedMessageBorderBrush", ColorEx.FromHex(0xFF151D26) },
                    { "ApplicationPageBackgroundThemeBrush", ColorEx.FromHex(0xFF1C2733) },
                    { "PageHeaderBackgroundBrush", ColorEx.FromHex(0xFF1C2733) },
                    { "PageSubHeaderBackgroundBrush", ColorEx.FromHex(0xFF1C2733) },
                    { "ContentDialogBackground", ColorEx.FromHex(0xFF1C2733) },
                    { "SolidBackgroundFillColorBaseBrush", ColorEx.FromHex(0xFF1C2733) },
                    { "TelegramSeparatorMediumBrush", ColorEx.FromHex(0xFF10171E) },
                    { "SystemControlDisabledChromeDisabledLowBrush", ColorEx.FromHex(0xFF7D8E98) },
                    { "ChatVerifiedBadgeBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatLastMessageStateBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatFromLabelBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatUnreadBadgeBrush", ColorEx.FromHex(0xFF5288C1) },
                    //{ "ChatUnreadBadgeMutedBrush", ColorEx.FromHex(0xFF7D8E98) },
                    //{ "ChatFailedBadgeBrush", ColorEx.FromHex(0xFFD32F2F) },
                    { "MessageBackgroundIncoming", ColorEx.FromHex(0xFF1C2733) },
                    { "MessageSubtleLabelIncoming", ColorEx.FromHex(0xFF7D8E98) },
                    { "MessageSubtleGlyphIncoming", ColorEx.FromHex(0xFF7D8E98) },
                    { "MessageSubtleForegroundOutgoing", ColorEx.FromHex(0xFF7DA8D3) },
                    { "MessageHeaderForegroundIncoming", ColorEx.FromHex(0xFF61A9E1) },
                    { "MessageHeaderBorderIncoming", ColorEx.FromHex(0xFF538EBD) },
                    { "MessageBackgroundOutgoing", ColorEx.FromHex(0xFF456A93) },
                    { "MessageSubtleLabelOutgoing", ColorEx.FromHex(0xFF91AFC8) },
                    { "MessageSubtleGlyphOutgoing", ColorEx.FromHex(0xFF86CAFF) },
                    { "MessageHeaderForegroundOutgoing", ColorEx.FromHex(0xFF90CBFF) },
                    { "MessageHeaderBorderOutgoing", ColorEx.FromHex(0xFF65BBF4) },
                    { "MessageMediaBackgroundIncoming", ColorEx.FromHex(0xFF3F96D0) },
                    { "MessageMediaBackgroundOutgoing", ColorEx.FromHex(0xFF4C9CE2) },
                    { "MessageReactionBackgroundOutgoing", ColorEx.FromHex(0x2B4153) },
                    { "MessageReactionForegroundOutgoing", ColorEx.FromHex(0x45A32D) },
                    { "MessageReactionChosenBackgroundOutgoing", ColorEx.FromHex(0x318EE4) },
                    { "MessageReactionBackgroundIncoming", ColorEx.FromHex(0x3A4754) },
                    { "MessageReactionForegroundIncoming", ColorEx.FromHex(0x168DCD) },
                    { "MessageReactionChosenBackgroundIncoming", ColorEx.FromHex(0x6EB2EE) },
                    { "MessageReactionChosenForegroundIncoming", ColorEx.FromHex(0x33393F) },
                }
            },
            {
                TelegramThemeType.Night, new Dictionary<string, Color>
                {
                    { "PinnedMessageForegroundBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "PageHeaderHighlightBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatVerifiedBadgeBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatLastMessageStateBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatFromLabelBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatUnreadBadgeBrush", ColorEx.FromHex(0xFF5288C1) },
                    //{ "ChatUnreadBadgeMutedBrush", ColorEx.FromHex(0xFF7D8E98) },
                    //{ "ChatFailedBadgeBrush", ColorEx.FromHex(0xFFD32F2F) },
                    { "MessageBackgroundIncoming", ColorEx.FromHex(0xFF1C2733) },
                    { "MessageSubtleLabelIncoming", ColorEx.FromHex(0xFF7D8E98) },
                    { "MessageSubtleGlyphIncoming", ColorEx.FromHex(0xFF7D8E98) },
                    { "MessageHeaderForegroundIncoming", ColorEx.FromHex(0xFF61A9E1) },
                    { "MessageHeaderBorderIncoming", ColorEx.FromHex(0xFF538EBD) },
                    { "MessageBackgroundOutgoing", ColorEx.FromHex(0xFF456A93) },
                    { "MessageSubtleForegroundOutgoing", ColorEx.FromHex(0xFF7DA8D3) },
                    { "MessageSubtleLabelOutgoing", ColorEx.FromHex(0xFF91AFC8) },
                    { "MessageSubtleGlyphOutgoing", ColorEx.FromHex(0xFF86CAFF) },
                    { "MessageHeaderForegroundOutgoing", ColorEx.FromHex(0xFF86CAFF) },
                    { "MessageHeaderBorderOutgoing", ColorEx.FromHex(0xFF86CAFF) },
                    { "MessageMediaBackgroundIncoming", ColorEx.FromHex(0xFF3F96D0) },
                    { "MessageMediaBackgroundOutgoing", ColorEx.FromHex(0xFF4C9CE2) },
                    { "MessageReactionBackgroundOutgoing", ColorEx.FromHex(0x2B4153) },
                    { "MessageReactionForegroundOutgoing", ColorEx.FromHex(0x45A32D) },
                    { "MessageReactionChosenBackgroundOutgoing", ColorEx.FromHex(0x318EE4) },
                    { "MessageReactionBackgroundIncoming", ColorEx.FromHex(0x3A4754) },
                    { "MessageReactionForegroundIncoming", ColorEx.FromHex(0x168DCD) },
                    { "MessageReactionChosenBackgroundIncoming", ColorEx.FromHex(0x6EB2EE) },
                    { "MessageReactionChosenForegroundIncoming", ColorEx.FromHex(0x33393F) },
                }
            },
            {
                TelegramThemeType.Day, new Dictionary<string, Color>
                {
                    { "PinnedMessageForegroundBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "PageHeaderHighlightBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatVerifiedBadgeBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatLastMessageStateBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatFromLabelBrush", ColorEx.FromHex(0xFF5288C1) },
                    { "ChatUnreadBadgeBrush", ColorEx.FromHex(0xFF5288C1) },
                    //{ "ChatUnreadBadgeMutedBrush", ColorEx.FromHex(0xFF7D8E98) },
                    //{ "ChatFailedBadgeBrush", ColorEx.FromHex(0xFFD32F2F) },
                    { "MessageSubtleLabelIncoming", ColorEx.FromHex(0xFF7D8E98) },
                    { "MessageSubtleGlyphIncoming", ColorEx.FromHex(0xFF7D8E98) },
                    { "MessageHeaderForegroundIncoming", ColorEx.FromHex(0xFF168dcd) },
                    { "MessageHeaderBorderIncoming", ColorEx.FromHex(0xFF538EBD) },
                    { "MessageBackgroundOutgoing", ColorEx.FromHex(0xFFDEF1FD) },
                    { "MessageSubtleForegroundOutgoing", ColorEx.FromHex(0xFF86A8C2) },
                    { "MessageSubtleLabelOutgoing", ColorEx.FromHex(0xFF91AFC8) },
                    { "MessageSubtleGlyphOutgoing", ColorEx.FromHex(0xFF86CAFF) },
                    { "MessageHeaderForegroundOutgoing", ColorEx.FromHex(0xFF168DCD) },
                    { "MessageHeaderBorderOutgoing", ColorEx.FromHex(0xFF05A0E8) },
                    { "MessageMediaBackgroundIncoming", ColorEx.FromHex(0xFF40A7E3) },
                    { "MessageMediaBackgroundOutgoing", ColorEx.FromHex(0xFF40A7E3) },
                    { "MessageReactionBackgroundOutgoing", ColorEx.FromHex(0xC1E4F8) },
                    { "MessageReactionForegroundOutgoing", ColorEx.FromHex(0x168DCD) },
                    { "MessageReactionChosenBackgroundOutgoing", ColorEx.FromHex(0x40A7E3) },
                }
            },
        };
    }

    public partial class ThemeService
    {
        private static readonly Dictionary<string, object> _defaultLight = new Dictionary<string, object>
        {
            { "MessageReactionBackgroundOutgoing", ColorEx.FromHex(0xD5F1C9) },
            { "MessageReactionForegroundOutgoing", ColorEx.FromHex(0x45A32D) },
            { "MessageReactionChosenBackgroundOutgoing", ColorEx.FromHex(0x5FBE67) },
            { "MessageReactionChosenForegroundOutgoing", ColorEx.FromHex(0xFFFFFF) },

            { "MessageReactionBackgroundIncoming", ColorEx.FromHex(0xE8F5FC) },
            { "MessageReactionForegroundIncoming", ColorEx.FromHex(0x168DCD) },
            { "MessageReactionChosenBackgroundIncoming", ColorEx.FromHex(0x40A7E3) },
            { "MessageReactionChosenForegroundIncoming", ColorEx.FromHex(0xFFFFFF) },

            { "ApplicationPageBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ChatPageBackgroundBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ContentDialogBackground", Color.FromArgb(0xFF, 0xF3, 0xF3, 0xF3) },
            { "PageHeaderForegroundBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "PageHeaderHighlightBrush", AccentShade.Default },
            { "PageHeaderDisabledBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "PageTitleBackgroundBrush", Color.FromArgb(0xFF, 0xF2, 0xF2, 0xF2) },
            { "PageHeaderBackgroundBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "PageHeaderBorderBrush", Color.FromArgb(0xFF, 0xF2, 0xF2, 0xF2) },
            { "PageSubHeaderBackgroundBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "PageBackgroundDarkBrush", Color.FromArgb(0xFF, 0xF2, 0xF2, 0xF2) },
            { "TelegramSeparatorMediumBrush", Color.FromArgb(0xFF, 0xF2, 0xF2, 0xF2) },
            { "TelegramBackgroundAccentBrush", AccentShade.Default },
            { "TelegramForegroundAccentBrush", AccentShade.Default },
            { "PinnedMessageForegroundBrush", AccentShade.Default },
            { "PinnedMessageBorderBrush", Color.FromArgb(0xFF, 0xE6, 0xE6, 0xE6) },
            { "TinyButtonBackgroundBrush", AccentShade.Default },
            { "ChatOnlineBadgeBrush", Color.FromArgb(0xFF, 0x00, 0xB1, 0x2C) },
            { "ChatVerifiedBadgeBrush", AccentShade.Default },
            { "ChatLastMessageStateBrush", AccentShade.Default },
            { "ChatFromLabelBrush", Color.FromArgb(0xFF, 0x3C, 0x7E, 0xB0) },
            { "ChatDraftLabelBrush", Color.FromArgb(0xFF, 0xDD, 0x4B, 0x39) },
            { "ChatUnreadBadgeMutedBrush", Color.FromArgb(0xFF, 0xBB, 0xBB, 0xBB) },
            { "ChatUnreadLabelMutedBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ChatFailedBadgeBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0x00) },
            { "ChatFailedLabelBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ChatUnreadBadgeBrush", AccentShade.Default },
            { "ChatUnreadLabelBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundAccentBrush", AccentShade.Default },
            { "SystemControlBackgroundAltHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundAltMediumHighBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundAltMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundAltMediumLowBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundBaseHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundBaseLowBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundBaseMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundBaseMediumHighBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundBaseMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundChromeBlackHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundChromeBlackMediumBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundChromeBlackLowBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundChromeBlackMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundChromeMediumBrush", Color.FromArgb(0xFF, 0xE6, 0xE6, 0xE6) },
            { "SystemControlBackgroundChromeMediumLowBrush", Color.FromArgb(0xFF, 0xF2, 0xF2, 0xF2) },
            { "SystemControlBackgroundChromeWhiteBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundListLowBrush", Color.FromArgb(0x19, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundListMediumBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlDisabledAccentBrush", AccentShade.Default },
            { "SystemControlDisabledBaseHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlDisabledBaseLowBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlDisabledBaseMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlDisabledChromeDisabledHighBrush", Color.FromArgb(0xFF, 0xCC, 0xCC, 0xCC) },
            { "SystemControlDisabledChromeDisabledLowBrush", Color.FromArgb(0xFF, 0x7A, 0x7A, 0x7A) },
            { "SystemControlDisabledChromeHighBrush", Color.FromArgb(0xFF, 0xCC, 0xCC, 0xCC) },
            { "SystemControlDisabledChromeMediumLowBrush", Color.FromArgb(0xFF, 0xF2, 0xF2, 0xF2) },
            { "SystemControlDisabledListMediumBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundAccentBrush", AccentShade.Default },
            { "SystemControlForegroundAltHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundAltMediumHighBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundBaseHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundBaseLowBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundBaseMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundBaseMediumHighBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundBaseMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundChromeBlackHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundChromeHighBrush", Color.FromArgb(0xFF, 0xCC, 0xCC, 0xCC) },
            { "SystemControlForegroundChromeMediumBrush", Color.FromArgb(0xFF, 0xE6, 0xE6, 0xE6) },
            { "SystemControlForegroundChromeDisabledLowBrush", Color.FromArgb(0xFF, 0x7A, 0x7A, 0x7A) },
            { "SystemControlForegroundChromeWhiteBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundChromeBlackMediumBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundChromeBlackMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundChromeGrayBrush", Color.FromArgb(0xFF, 0x76, 0x76, 0x76) },
            { "SystemControlForegroundListLowBrush", Color.FromArgb(0x19, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundListMediumBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightAccentBrush", AccentShade.Default },
            { "SystemControlHighlightAltAccentBrush", AccentShade.Default },
            { "SystemControlHighlightAltAltHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightAltBaseHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightAltBaseLowBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightAltBaseMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightAltBaseMediumHighBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightAltAltMediumHighBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightAltBaseMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightAltListAccentHighBrush", AccentShade.Default },
            { "SystemControlHighlightAltListAccentLowBrush", AccentShade.Default },
            { "SystemControlHighlightAltListAccentMediumBrush", AccentShade.Default },
            { "SystemControlHighlightAltChromeWhiteBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightBaseHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightBaseLowBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightBaseMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightBaseMediumHighBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightBaseMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightChromeAltLowBrush", Color.FromArgb(0xFF, 0x17, 0x17, 0x17) },
            { "SystemControlHighlightChromeHighBrush", Color.FromArgb(0xFF, 0xCC, 0xCC, 0xCC) },
            { "SystemControlHighlightListAccentHighBrush", AccentShade.Default },
            { "SystemControlHighlightListAccentLowBrush", AccentShade.Default },
            { "SystemControlHighlightListAccentMediumBrush", AccentShade.Default },
            { "SystemControlHighlightListMediumBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightListLowBrush", Color.FromArgb(0x19, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightChromeWhiteBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHyperlinkTextBrush", AccentShade.Default },
            { "SystemControlHyperlinkBaseHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlHyperlinkBaseMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlHyperlinkBaseMediumHighBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlPageBackgroundAltMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlPageBackgroundAltHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlPageBackgroundMediumAltMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlPageBackgroundBaseLowBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlPageBackgroundBaseMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlPageBackgroundListLowBrush", Color.FromArgb(0x19, 0x00, 0x00, 0x00) },
            { "SystemControlPageBackgroundChromeLowBrush", Color.FromArgb(0xFF, 0xF2, 0xF2, 0xF2) },
            { "SystemControlPageBackgroundChromeMediumLowBrush", Color.FromArgb(0xFF, 0xF2, 0xF2, 0xF2) },
            { "SystemControlPageTextBaseHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlPageTextBaseMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlPageTextChromeBlackMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightListAccentVeryHighBrush", AccentShade.Default },
            { "SystemControlHighlightListAccentMediumLowBrush", AccentShade.Default },
            { "TextFillColorPrimaryBrush", Color.FromArgb(0xE4, 0x00, 0x00, 0x00) },
            { "TextFillColorSecondaryBrush", Color.FromArgb(0x93, 0x00, 0x00, 0x00) },
            { "TextFillColorTertiaryBrush", Color.FromArgb(0x72, 0x00, 0x00, 0x00) },
            { "TextFillColorDisabledBrush", Color.FromArgb(0x5C, 0x00, 0x00, 0x00) },
            { "TextFillColorInverseBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "AccentTextFillColorPrimaryBrush", AccentShade.Dark2 },
            { "AccentTextFillColorSecondaryBrush", AccentShade.Dark3 },
            { "AccentTextFillColorTertiaryBrush", AccentShade.Dark1 },
            { "AccentTextFillColorDisabledBrush", Color.FromArgb(0x5C, 0x00, 0x00, 0x00) },
            { "TextOnAccentFillColorSelectedTextBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextOnAccentFillColorPrimaryBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextOnAccentFillColorSecondaryBrush", Color.FromArgb(0xB3, 0xFF, 0xFF, 0xFF) },
            { "TextOnAccentFillColorDisabledBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ControlFillColorDefaultBrush", Color.FromArgb(0xB3, 0xFF, 0xFF, 0xFF) },
            { "ControlFillColorSecondaryBrush", Color.FromArgb(0x80, 0xF9, 0xF9, 0xF9) },
            { "ControlFillColorTertiaryBrush", Color.FromArgb(0x4D, 0xF9, 0xF9, 0xF9) },
            { "ControlFillColorDisabledBrush", Color.FromArgb(0x4D, 0xF9, 0xF9, 0xF9) },
            { "ControlFillColorTransparentBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "ControlFillColorInputActiveBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ControlStrongFillColorDefaultBrush", Color.FromArgb(0x72, 0x00, 0x00, 0x00) },
            { "ControlStrongFillColorDisabledBrush", Color.FromArgb(0x51, 0x00, 0x00, 0x00) },
            { "ControlSolidFillColorDefaultBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SubtleFillColorTransparentBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "SubtleFillColorSecondaryBrush", Color.FromArgb(0x09, 0x00, 0x00, 0x00) },
            { "SubtleFillColorTertiaryBrush", Color.FromArgb(0x06, 0x00, 0x00, 0x00) },
            { "SubtleFillColorDisabledBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "ControlAltFillColorTransparentBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "ControlAltFillColorSecondaryBrush", Color.FromArgb(0x06, 0x00, 0x00, 0x00) },
            { "ControlAltFillColorTertiaryBrush", Color.FromArgb(0x0F, 0x00, 0x00, 0x00) },
            { "ControlAltFillColorQuarternaryBrush", Color.FromArgb(0x18, 0x00, 0x00, 0x00) },
            { "ControlAltFillColorDisabledBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "ControlOnImageFillColorDefaultBrush", Color.FromArgb(0xC9, 0xFF, 0xFF, 0xFF) },
            { "ControlOnImageFillColorSecondaryBrush", Color.FromArgb(0xFF, 0xF3, 0xF3, 0xF3) },
            { "ControlOnImageFillColorTertiaryBrush", Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB) },
            { "ControlOnImageFillColorDisabledBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "AccentFillColorSelectedTextBackgroundBrush", AccentShade.Default },
            { "AccentFillColorDefaultBrush", AccentShade.Dark1 },
            { "AccentFillColorSecondaryBrush", AccentShade.Dark1 },
            { "AccentFillColorTertiaryBrush", AccentShade.Dark1 },
            { "AccentFillColorDisabledBrush", Color.FromArgb(0x37, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorDefaultBrush", Color.FromArgb(0x0F, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorSecondaryBrush", Color.FromArgb(0x29, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorOnAccentDefaultBrush", Color.FromArgb(0x14, 0xFF, 0xFF, 0xFF) },
            { "ControlStrokeColorOnAccentSecondaryBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorOnAccentTertiaryBrush", Color.FromArgb(0x37, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorOnAccentDisabledBrush", Color.FromArgb(0x0F, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorForStrongFillWhenOnImageBrush", Color.FromArgb(0x59, 0xFF, 0xFF, 0xFF) },
            { "CardStrokeColorDefaultBrush", Color.FromArgb(0x0F, 0x00, 0x00, 0x00) },
            { "CardStrokeColorDefaultSolidBrush", Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB) },
            { "ControlStrongStrokeColorDefaultBrush", Color.FromArgb(0x72, 0x00, 0x00, 0x00) },
            { "ControlStrongStrokeColorDisabledBrush", Color.FromArgb(0x37, 0x00, 0x00, 0x00) },
            { "SurfaceStrokeColorDefaultBrush", Color.FromArgb(0x0F, 0x00, 0x00, 0x00) },
            { "SurfaceStrokeColorFlyoutBrush", Color.FromArgb(0x0F, 0x00, 0x00, 0x00) },
            { "SurfaceStrokeColorInverseBrush", Color.FromArgb(0x15, 0xFF, 0xFF, 0xFF) },
            { "DividerStrokeColorDefaultBrush", Color.FromArgb(0x0F, 0x00, 0x00, 0x00) },
            { "FocusStrokeColorOuterBrush", Color.FromArgb(0xE4, 0x00, 0x00, 0x00) },
            { "FocusStrokeColorInnerBrush", Color.FromArgb(0xB3, 0xFF, 0xFF, 0xFF) },
            { "CardBackgroundFillColorDefaultBrush", Color.FromArgb(0xB3, 0xFF, 0xFF, 0xFF) },
            { "CardBackgroundFillColorSecondaryBrush", Color.FromArgb(0x80, 0xF6, 0xF6, 0xF6) },
            { "SmokeFillColorDefaultBrush", Color.FromArgb(0x4D, 0xFF, 0xFF, 0xFF) },
            { "LayerFillColorDefaultBrush", Color.FromArgb(0x80, 0xFF, 0xFF, 0xFF) },
            { "LayerFillColorAltBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "LayerOnAcrylicFillColorDefaultBrush", Color.FromArgb(0x40, 0xFF, 0xFF, 0xFF) },
            { "LayerOnAccentAcrylicFillColorDefaultBrush", Color.FromArgb(0x40, 0xFF, 0xFF, 0xFF) },
            { "SolidBackgroundFillColorBaseBrush", Color.FromArgb(0xFF, 0xF3, 0xF3, 0xF3) },
            { "SolidBackgroundFillColorSecondaryBrush", Color.FromArgb(0xFF, 0xEE, 0xEE, 0xEE) },
            { "SolidBackgroundFillColorTertiaryBrush", Color.FromArgb(0xFF, 0xF9, 0xF9, 0xF9) },
            { "SolidBackgroundFillColorQuarternaryBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemFillColorAttentionBrush", AccentShade.Default },
            { "SystemFillColorSuccessBrush", Color.FromArgb(0xFF, 0x0F, 0x7B, 0x0F) },
            { "SystemFillColorCautionBrush", Color.FromArgb(0xFF, 0x9D, 0x5D, 0x00) },
            { "SystemFillColorCriticalBrush", Color.FromArgb(0xFF, 0xC4, 0x2B, 0x1C) },
            { "SystemFillColorNeutralBrush", Color.FromArgb(0x72, 0x00, 0x00, 0x00) },
            { "SystemFillColorAttentionBackgroundBrush", Color.FromArgb(0x80, 0xF6, 0xF6, 0xF6) },
            { "SystemFillColorSuccessBackgroundBrush", Color.FromArgb(0xFF, 0xDF, 0xF6, 0xDD) },
            { "SystemFillColorCautionBackgroundBrush", Color.FromArgb(0xFF, 0xFF, 0xF4, 0xCE) },
            { "SystemFillColorCriticalBackgroundBrush", Color.FromArgb(0xFF, 0xFD, 0xE7, 0xE9) },
            { "SystemFillColorNeutralBackgroundBrush", Color.FromArgb(0x06, 0x00, 0x00, 0x00) },
            { "SystemColorWindowTextColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorWindowColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorButtonFaceColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorButtonTextColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorHighlightColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorHighlightTextColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorHotlightColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorGrayTextColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "TextOnAccentFillColorDefaultBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextOnAccentAAFillColorPrimaryBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextOnAccentAAFillColorSecondaryBrush", Color.FromArgb(0xB3, 0xFF, 0xFF, 0xFF) },
            { "TextOnAccentAAFillColorDisabledBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ControlAAFillColorDefaultBrush", Color.FromArgb(0x72, 0x00, 0x00, 0x00) },
            { "ControlAAFillColorDisabledBrush", Color.FromArgb(0x51, 0x00, 0x00, 0x00) },
            { "AccentAAFillColorDefaultBrush", AccentShade.Dark1 },
            { "AccentAAFillColorSecondaryBrush", AccentShade.Dark2 },
            { "AccentAAFillColorTertiaryBrush", AccentShade.Default },
            { "AccentAAFillColorDisabledBrush", Color.FromArgb(0x37, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorForAAFillOnImageBrush", Color.FromArgb(0x59, 0xFF, 0xFF, 0xFF) },
            { "ControlAAStrokeColorDefaultBrush", Color.FromArgb(0x72, 0x00, 0x00, 0x00) },
            { "ControlAAStrokeColorDisabledBrush", Color.FromArgb(0x37, 0x00, 0x00, 0x00) },
            { "MenuFlyoutItemFocusedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xE5, 0xE5, 0xE5) },
            { "MenuFlyoutItemFocusedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "MenuFlyoutItemDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "MenuFlyoutItemPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xE5, 0xE5, 0xE5) },
            { "MenuFlyoutItemPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "MenuFlyoutItemPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "MenuFlyoutItemPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "MenuFlyoutSeparatorThemeBrush", Color.FromArgb(0xFF, 0x7A, 0x7A, 0x7A) },
            { "SystemControlTransientBorderBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ProgressBarIndeterminateForegroundThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ContentDialogBorderThemeBrush", AccentShade.Default },
            { "ContentDialogDimmingThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "InkToolbarFlyoutItemBorderSelectedThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RadioButtonBackgroundThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonBorderThemeBrush", Color.FromArgb(0x45, 0x00, 0x00, 0x00) },
            { "RadioButtonContentDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "RadioButtonContentForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RadioButtonDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xCA, 0xCA, 0xCA) },
            { "RadioButtonDisabledBorderThemeBrush", Color.FromArgb(0x26, 0x00, 0x00, 0x00) },
            { "RadioButtonDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "RadioButtonForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RadioButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xDE, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonPointerOverBorderThemeBrush", Color.FromArgb(0x70, 0x00, 0x00, 0x00) },
            { "RadioButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RadioButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RadioButtonPressedBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RadioButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonCheckedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedDisabledForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonCheckedPointerOverBackgroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedPointerOverBorderThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedPressedBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0x3D, 0x00, 0x00, 0x00) },
            { "ListBoxBackgroundThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "ListBoxBorderThemeBrush", Color.FromArgb(0x45, 0x00, 0x00, 0x00) },
            { "ListBoxDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ListBoxFocusBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListBoxForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ListBoxItemDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ListBoxItemPointerOverBackgroundThemeBrush", Color.FromArgb(0x21, 0x00, 0x00, 0x00) },
            { "ListBoxItemPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ListBoxItemPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xD3, 0xD3, 0xD3) },
            { "ListBoxItemPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ListBoxItemSelectedDisabledBackgroundThemeBrush", Color.FromArgb(0x8C, 0x00, 0x00, 0x00) },
            { "ListBoxItemSelectedDisabledForegroundThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "ListBoxItemSelectedPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
            { "ToggleSwitchCurtainBackgroundThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ToggleSwitchCurtainPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
            { "ToggleSwitchCurtainPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x72, 0x41, 0xE4) },
            { "ToggleSwitchDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ToggleSwitchForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleSwitchHeaderDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ToggleSwitchHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleSwitchOuterBorderBorderThemeBrush", Color.FromArgb(0x59, 0x00, 0x00, 0x00) },
            { "ToggleSwitchOuterBorderDisabledBorderThemeBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "ToggleSwitchThumbBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleSwitchThumbBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleSwitchThumbDisabledBackgroundThemeBrush", Color.FromArgb(0xFF, 0x92, 0x92, 0x92) },
            { "ToggleSwitchThumbDisabledBorderThemeBrush", Color.FromArgb(0xFF, 0x92, 0x92, 0x92) },
            { "ToggleSwitchThumbPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleSwitchThumbPointerOverBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleSwitchThumbPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleSwitchThumbPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleSwitchTrackBackgroundThemeBrush", Color.FromArgb(0x59, 0x00, 0x00, 0x00) },
            { "ToggleSwitchTrackDisabledBackgroundThemeBrush", Color.FromArgb(0x1F, 0x00, 0x00, 0x00) },
            { "ToggleSwitchTrackPointerOverBackgroundThemeBrush", Color.FromArgb(0x4A, 0x00, 0x00, 0x00) },
            { "ToggleSwitchTrackPressedBackgroundThemeBrush", Color.FromArgb(0x42, 0x00, 0x00, 0x00) },
            { "ListViewItemCheckHintThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ListViewItemCheckSelectingThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ListViewItemCheckThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemDragBackgroundThemeBrush", Color.FromArgb(0x99, 0x46, 0x17, 0xB4) },
            { "ListViewItemFocusBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ListViewItemOverlayBackgroundThemeBrush", Color.FromArgb(0xA6, 0x00, 0x00, 0x00) },
            { "ListViewItemOverlaySecondaryForegroundThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemOverlayForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemPlaceholderBackgroundThemeBrush", Color.FromArgb(0xFF, 0x3D, 0x3D, 0x3D) },
            { "ListViewItemPointerOverBackgroundThemeBrush", Color.FromArgb(0x4D, 0x00, 0x00, 0x00) },
            { "ListViewItemSelectedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ListViewItemSelectedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ListViewItemSelectedPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
            { "ListViewItemSelectedPointerOverBorderThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
            { "TextBoxForegroundHeaderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "TextBoxPlaceholderTextThemeBrush", Color.FromArgb(0xAB, 0x00, 0x00, 0x00) },
            { "TextBoxBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextBoxBorderThemeBrush", Color.FromArgb(0xA3, 0x00, 0x00, 0x00) },
            { "TextBoxButtonForegroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "TextBoxButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xDE, 0xDE, 0xDE) },
            { "TextBoxButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "TextBoxButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextBoxDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xCA, 0xCA, 0xCA) },
            { "TextBoxDisabledBorderThemeBrush", Color.FromArgb(0x26, 0x00, 0x00, 0x00) },
            { "TextBoxDisabledForegroundThemeBrush", Color.FromArgb(0xFF, 0x66, 0x66, 0x66) },
            { "TextBoxForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ButtonBackgroundThemeBrush", Color.FromArgb(0xB3, 0xB6, 0xB6, 0xB6) },
            { "ButtonBorderThemeBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "ButtonDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xCA, 0xCA, 0xCA) },
            { "ButtonDisabledBorderThemeBrush", Color.FromArgb(0x1A, 0x00, 0x00, 0x00) },
            { "ButtonDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ButtonForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xD1, 0xCD, 0xCD, 0xCD) },
            { "ButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonCheckedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonCheckedBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonCheckedDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ToggleButtonCheckedDisabledForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonCheckedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonCheckedPointerOverBackgroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ToggleButtonCheckedPointerOverBorderThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ToggleButtonCheckedPressedBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonCheckedPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonDisabledBorderThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ToggleButtonDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ToggleButtonForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0x21, 0x00, 0x00, 0x00) },
            { "ToggleButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "RepeatButtonBorderThemeBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "RepeatButtonDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xCA, 0xCA, 0xCA) },
            { "RepeatButtonDisabledBorderThemeBrush", Color.FromArgb(0x1A, 0x00, 0x00, 0x00) },
            { "RepeatButtonDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "RepeatButtonForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RepeatButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xD1, 0xCD, 0xCD, 0xCD) },
            { "RepeatButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RepeatButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RepeatButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxBackgroundThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxBorderThemeBrush", Color.FromArgb(0x45, 0x00, 0x00, 0x00) },
            { "CheckBoxContentDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "CheckBoxContentForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "CheckBoxDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xCA, 0xCA, 0xCA) },
            { "CheckBoxDisabledBorderThemeBrush", Color.FromArgb(0x26, 0x00, 0x00, 0x00) },
            { "CheckBoxDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "CheckBoxForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "CheckBoxPointerOverBackgroundThemeBrush", Color.FromArgb(0xDE, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "CheckBoxPointerOverBorderThemeBrush", Color.FromArgb(0x70, 0x00, 0x00, 0x00) },
            { "CheckBoxPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "CheckBoxPressedBorderThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "CheckBoxPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "DatePickerHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "DatePickerForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "FlipViewButtonBackgroundThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "FlipViewButtonBorderThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "FlipViewButtonForegroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "FlipViewButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xF0, 0xD7, 0xD7, 0xD7) },
            { "FlipViewButtonPointerOverBorderThemeBrush", Color.FromArgb(0x9E, 0xC1, 0xC1, 0xC1) },
            { "FlipViewButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "FlipViewButtonPressedBackgroundThemeBrush", Color.FromArgb(0xBD, 0x29, 0x29, 0x29) },
            { "FlipViewButtonPressedBorderThemeBrush", Color.FromArgb(0xBD, 0x29, 0x29, 0x29) },
            { "FlipViewButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "PivotForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "PivotHeaderForegroundSelectedBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "PivotHeaderForegroundUnselectedBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "PivotNavButtonBackgroundThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "PivotNavButtonBorderThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "PivotNavButtonForegroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "PivotNavButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xF0, 0xD7, 0xD7, 0xD7) },
            { "PivotNavButtonPointerOverBorderThemeBrush", Color.FromArgb(0x9E, 0xC1, 0xC1, 0xC1) },
            { "PivotNavButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "PivotNavButtonPressedBackgroundThemeBrush", Color.FromArgb(0xBD, 0x29, 0x29, 0x29) },
            { "PivotNavButtonPressedBorderThemeBrush", Color.FromArgb(0xBD, 0x29, 0x29, 0x29) },
            { "PivotNavButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ScrollBarButtonForegroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ScrollBarButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xDA, 0xDA, 0xDA) },
            { "ScrollBarButtonPointerOverBorderThemeBrush", Color.FromArgb(0xFF, 0xDA, 0xDA, 0xDA) },
            { "ScrollBarButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ScrollBarButtonPressedBackgroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ScrollBarButtonPressedBorderThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ScrollBarButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ScrollBarPanningBackgroundThemeBrush", Color.FromArgb(0xFF, 0xCD, 0xCD, 0xCD) },
            { "ScrollBarPanningBorderThemeBrush", Color.FromArgb(0x7D, 0x9A, 0x9A, 0x9A) },
            { "ScrollBarThumbBackgroundThemeBrush", Color.FromArgb(0xFF, 0xCD, 0xCD, 0xCD) },
            { "ScrollBarThumbBorderThemeBrush", Color.FromArgb(0x3B, 0x55, 0x55, 0x55) },
            { "ScrollBarThumbPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xDA, 0xDA, 0xDA) },
            { "ScrollBarThumbPointerOverBorderThemeBrush", Color.FromArgb(0x6B, 0xB7, 0xB7, 0xB7) },
            { "ScrollBarThumbPressedBackgroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ScrollBarThumbPressedBorderThemeBrush", Color.FromArgb(0xED, 0x55, 0x55, 0x55) },
            { "ScrollBarTrackBackgroundThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "ScrollBarTrackBorderThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "SliderThumbBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbDisabledBackgroundThemeBrush", Color.FromArgb(0xFF, 0x7E, 0x7E, 0x7E) },
            { "SliderThumbPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbPointerOverBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbPressedBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderTickmarkOutsideBackgroundThemeBrush", Color.FromArgb(0x80, 0xFF, 0xFF, 0xFF) },
            { "SliderTickMarkOutsideDisabledForegroundThemeBrush", Color.FromArgb(0x80, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackBackgroundThemeBrush", Color.FromArgb(0x29, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackDecreaseBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5B, 0x2E, 0xC5) },
            { "SliderTrackDecreaseDisabledBackgroundThemeBrush", Color.FromArgb(0x1F, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackDecreasePointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x72, 0x4B, 0xCD) },
            { "SliderTrackDecreasePressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x81, 0x52, 0xEF) },
            { "SliderTrackDisabledBackgroundThemeBrush", Color.FromArgb(0x29, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackPointerOverBackgroundThemeBrush", Color.FromArgb(0x46, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackPressedBackgroundThemeBrush", Color.FromArgb(0x59, 0xFF, 0xFF, 0xFF) },
            { "SliderHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TimePickerForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "TimePickerHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToolTipBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToolTipBorderThemeBrush", Color.FromArgb(0xFF, 0x80, 0x80, 0x80) },
            { "ToolTipForegroundThemeBrush", Color.FromArgb(0xFF, 0x66, 0x66, 0x66) },
            { "PersonPictureForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "PersonPictureEllipseBadgeForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "PersonPictureEllipseBadgeFillThemeBrush", Color.FromArgb(0xFF, 0xCC, 0xCC, 0xCC) },
            { "PersonPictureEllipseBadgeStrokeThemeBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "PersonPictureEllipseFillThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "TeachingTipTopHighlightBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxArrowDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ComboBoxArrowForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxArrowPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxBackgroundThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxBorderThemeBrush", Color.FromArgb(0x45, 0x00, 0x00, 0x00) },
            { "ComboBoxDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xCA, 0xCA, 0xCA) },
            { "ComboBoxDisabledBorderThemeBrush", Color.FromArgb(0x26, 0x00, 0x00, 0x00) },
            { "ComboBoxDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ComboBoxFocusedBorderThemeBrush", Color.FromArgb(0x70, 0x00, 0x00, 0x00) },
            { "ComboBoxForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxItemDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ComboBoxItemPointerOverBackgroundThemeBrush", Color.FromArgb(0x21, 0x00, 0x00, 0x00) },
            { "ComboBoxItemPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxItemPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xD3, 0xD3, 0xD3) },
            { "ComboBoxItemPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxItemSelectedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ComboBoxItemSelectedDisabledBackgroundThemeBrush", Color.FromArgb(0x8C, 0x00, 0x00, 0x00) },
            { "ComboBoxItemSelectedDisabledForegroundThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxItemSelectedPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
            { "ComboBoxPlaceholderTextForegroundThemeBrush", Color.FromArgb(0x88, 0x00, 0x00, 0x00) },
            { "ComboBoxPointerOverBackgroundThemeBrush", Color.FromArgb(0xDE, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxPointerOverBorderThemeBrush", Color.FromArgb(0x70, 0x00, 0x00, 0x00) },
            { "ComboBoxPopupBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxPopupBorderThemeBrush", Color.FromArgb(0xFF, 0x21, 0x21, 0x21) },
            { "ComboBoxPopupForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxPressedBorderThemeBrush", Color.FromArgb(0xA3, 0x00, 0x00, 0x00) },
            { "ComboBoxPressedHighlightThemeBrush", Color.FromArgb(0xFF, 0xD3, 0xD3, 0xD3) },
            { "ComboBoxPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxSelectedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ComboBoxSelectedPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
        };

        private static readonly Dictionary<string, object> _defaultDark = new Dictionary<string, object>
        {
            { "MessageReactionBackgroundOutgoing", ColorEx.FromHex(0x2B4153) },
            { "MessageReactionForegroundOutgoing", ColorEx.FromHex(0x7AC3F4) },
            { "MessageReactionChosenBackgroundOutgoing", ColorEx.FromHex(0x318EE4) },
            { "MessageReactionChosenForegroundOutgoing", ColorEx.FromHex(0x33393F) },

            { "MessageReactionBackgroundIncoming", ColorEx.FromHex(0x3A4754) },
            { "MessageReactionForegroundIncoming", ColorEx.FromHex(0x67BBF3) },
            { "MessageReactionChosenBackgroundIncoming", ColorEx.FromHex(0x6EB2EE) },
            { "MessageReactionChosenForegroundIncoming", ColorEx.FromHex(0x33393F) },

            { "ApplicationPageBackgroundThemeBrush", Color.FromArgb(0xFF, 0x17, 0x17, 0x17) },
            { "ChatPageBackgroundBrush", Color.FromArgb(0xFF, 0x17, 0x17, 0x17) },
            { "ContentDialogBackground", Color.FromArgb(0xFF, 0x20, 0x20, 0x20) },
            { "PageHeaderForegroundBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "PageHeaderHighlightBrush", AccentShade.Default },
            { "PageHeaderDisabledBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "PageTitleBackgroundBrush", Color.FromArgb(0xFF, 0x2B, 0x2B, 0x2B) },
            { "PageHeaderBackgroundBrush", Color.FromArgb(0xFF, 0x17, 0x17, 0x17) },
            { "PageHeaderBorderBrush", Color.FromArgb(0xFF, 0x1F, 0x1F, 0x1F) },
            { "PageSubHeaderBackgroundBrush", Color.FromArgb(0xFF, 0x17, 0x17, 0x17) },
            { "PageBackgroundDarkBrush", Color.FromArgb(0xFF, 0x1F, 0x1F, 0x1F) },
            { "TelegramSeparatorMediumBrush", Color.FromArgb(0xFF, 0x1F, 0x1F, 0x1F) },
            { "TelegramBackgroundAccentBrush", AccentShade.Default },
            { "TelegramForegroundAccentBrush", AccentShade.Default },
            { "PinnedMessageForegroundBrush", AccentShade.Default },
            { "PinnedMessageBorderBrush", Color.FromArgb(0xFF, 0x1F, 0x1F, 0x1F) },
            { "TinyButtonBackgroundBrush", AccentShade.Default },
            { "ChatOnlineBadgeBrush", Color.FromArgb(0xFF, 0x89, 0xDF, 0x9E) },
            { "ChatVerifiedBadgeBrush", AccentShade.Default },
            { "ChatLastMessageStateBrush", AccentShade.Default },
            { "ChatFromLabelBrush", AccentShade.Default },
            { "ChatDraftLabelBrush", Color.FromArgb(0xFF, 0xDD, 0x4B, 0x39) },
            { "ChatUnreadBadgeMutedBrush", Color.FromArgb(0xFF, 0x44, 0x44, 0x44) },
            { "ChatUnreadLabelMutedBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ChatFailedBadgeBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0x00) },
            { "ChatFailedLabelBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ChatUnreadBadgeBrush", AccentShade.Default },
            { "ChatUnreadLabelBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundAccentBrush", AccentShade.Default },
            { "SystemControlBackgroundAltHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundAltMediumHighBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundAltMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundAltMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundBaseHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundBaseLowBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundBaseMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundBaseMediumHighBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundBaseMediumLowBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundChromeBlackHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundChromeBlackMediumBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundChromeBlackLowBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundChromeBlackMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlBackgroundChromeMediumBrush", Color.FromArgb(0xFF, 0x1F, 0x1F, 0x1F) },
            { "SystemControlBackgroundChromeMediumLowBrush", Color.FromArgb(0xFF, 0x2B, 0x2B, 0x2B) },
            { "SystemControlBackgroundChromeWhiteBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundListLowBrush", Color.FromArgb(0x19, 0xFF, 0xFF, 0xFF) },
            { "SystemControlBackgroundListMediumBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlDisabledAccentBrush", AccentShade.Default },
            { "SystemControlDisabledBaseHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlDisabledBaseLowBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlDisabledBaseMediumLowBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "SystemControlDisabledChromeDisabledHighBrush", Color.FromArgb(0xFF, 0x33, 0x33, 0x33) },
            { "SystemControlDisabledChromeDisabledLowBrush", Color.FromArgb(0xFF, 0x85, 0x85, 0x85) },
            { "SystemControlDisabledChromeHighBrush", Color.FromArgb(0xFF, 0x76, 0x76, 0x76) },
            { "SystemControlDisabledChromeMediumLowBrush", Color.FromArgb(0xFF, 0x2B, 0x2B, 0x2B) },
            { "SystemControlDisabledListMediumBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlRevealFocusVisualBrush", AccentShade.Default },
            { "SystemControlForegroundAccentBrush", AccentShade.Default },
            { "SystemControlForegroundAltHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundAltMediumHighBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundBaseHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundBaseLowBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundBaseMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundBaseMediumHighBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundBaseMediumLowBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundChromeBlackHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundChromeHighBrush", Color.FromArgb(0xFF, 0x76, 0x76, 0x76) },
            { "SystemControlForegroundChromeMediumBrush", Color.FromArgb(0xFF, 0x1F, 0x1F, 0x1F) },
            { "SystemControlForegroundChromeWhiteBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundChromeDisabledLowBrush", Color.FromArgb(0xFF, 0x85, 0x85, 0x85) },
            { "SystemControlForegroundChromeGrayBrush", Color.FromArgb(0xFF, 0x76, 0x76, 0x76) },
            { "SystemControlForegroundListLowBrush", Color.FromArgb(0x19, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundListMediumBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlForegroundChromeBlackMediumBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlForegroundChromeBlackMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightAccentBrush", AccentShade.Default },
            { "SystemControlHighlightAltAccentBrush", AccentShade.Default },
            { "SystemControlHighlightAltAltHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightAltBaseHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightAltBaseLowBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightAltBaseMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightAltBaseMediumHighBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightAltAltMediumHighBrush", Color.FromArgb(0xCC, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightAltBaseMediumLowBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightAltListAccentHighBrush", AccentShade.Default },
            { "SystemControlHighlightAltListAccentLowBrush", AccentShade.Default },
            { "SystemControlHighlightAltListAccentMediumBrush", AccentShade.Default },
            { "SystemControlHighlightAltChromeWhiteBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightBaseHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightBaseLowBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightBaseMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightBaseMediumHighBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightBaseMediumLowBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightChromeAltLowBrush", Color.FromArgb(0xFF, 0xF2, 0xF2, 0xF2) },
            { "SystemControlHighlightChromeHighBrush", Color.FromArgb(0xFF, 0x76, 0x76, 0x76) },
            { "SystemControlHighlightListAccentHighBrush", AccentShade.Default },
            { "SystemControlHighlightListAccentLowBrush", AccentShade.Default },
            { "SystemControlHighlightListAccentMediumBrush", AccentShade.Default },
            { "SystemControlHighlightListMediumBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightListLowBrush", Color.FromArgb(0x19, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHighlightChromeWhiteBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHyperlinkTextBrush", AccentShade.Default },
            { "SystemControlHyperlinkBaseHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHyperlinkBaseMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlHyperlinkBaseMediumHighBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "SystemControlPageBackgroundAltMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlPageBackgroundAltHighBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "SystemControlPageBackgroundMediumAltMediumBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "SystemControlPageBackgroundBaseLowBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "SystemControlPageBackgroundBaseMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlPageBackgroundListLowBrush", Color.FromArgb(0x19, 0xFF, 0xFF, 0xFF) },
            { "SystemControlPageBackgroundChromeLowBrush", Color.FromArgb(0xFF, 0x17, 0x17, 0x17) },
            { "SystemControlPageBackgroundChromeMediumLowBrush", Color.FromArgb(0xFF, 0x2B, 0x2B, 0x2B) },
            { "SystemControlPageTextBaseHighBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SystemControlPageTextBaseMediumBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "SystemControlPageTextChromeBlackMediumLowBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "SystemControlHighlightListAccentVeryHighBrush", AccentShade.Default },
            { "SystemControlHighlightListAccentMediumLowBrush", AccentShade.Default },
            { "TextFillColorPrimaryBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextFillColorSecondaryBrush", Color.FromArgb(0xC5, 0xFF, 0xFF, 0xFF) },
            { "TextFillColorTertiaryBrush", Color.FromArgb(0x87, 0xFF, 0xFF, 0xFF) },
            { "TextFillColorDisabledBrush", Color.FromArgb(0x5D, 0xFF, 0xFF, 0xFF) },
            { "TextFillColorInverseBrush", Color.FromArgb(0xE4, 0x00, 0x00, 0x00) },
            { "AccentTextFillColorPrimaryBrush", AccentShade.Light3 },
            { "AccentTextFillColorSecondaryBrush", AccentShade.Light3 },
            { "AccentTextFillColorTertiaryBrush", AccentShade.Light2 },
            { "AccentTextFillColorDisabledBrush", Color.FromArgb(0x5D, 0xFF, 0xFF, 0xFF) },
            { "TextOnAccentFillColorSelectedTextBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextOnAccentFillColorPrimaryBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "TextOnAccentFillColorSecondaryBrush", Color.FromArgb(0x80, 0x00, 0x00, 0x00) },
            { "TextOnAccentFillColorDisabledBrush", Color.FromArgb(0x87, 0xFF, 0xFF, 0xFF) },
            { "ControlFillColorDefaultBrush", Color.FromArgb(0x0F, 0xFF, 0xFF, 0xFF) },
            { "ControlFillColorSecondaryBrush", Color.FromArgb(0x15, 0xFF, 0xFF, 0xFF) },
            { "ControlFillColorTertiaryBrush", Color.FromArgb(0x08, 0xFF, 0xFF, 0xFF) },
            { "ControlFillColorDisabledBrush", Color.FromArgb(0x0B, 0xFF, 0xFF, 0xFF) },
            { "ControlFillColorTransparentBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "ControlFillColorInputActiveBrush", Color.FromArgb(0xB3, 0x1E, 0x1E, 0x1E) },
            { "ControlStrongFillColorDefaultBrush", Color.FromArgb(0x8B, 0xFF, 0xFF, 0xFF) },
            { "ControlStrongFillColorDisabledBrush", Color.FromArgb(0x3F, 0xFF, 0xFF, 0xFF) },
            { "ControlSolidFillColorDefaultBrush", Color.FromArgb(0xFF, 0x45, 0x45, 0x45) },
            { "SubtleFillColorTransparentBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "SubtleFillColorSecondaryBrush", Color.FromArgb(0x0F, 0xFF, 0xFF, 0xFF) },
            { "SubtleFillColorTertiaryBrush", Color.FromArgb(0x0A, 0xFF, 0xFF, 0xFF) },
            { "SubtleFillColorDisabledBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "ControlAltFillColorTransparentBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "ControlAltFillColorSecondaryBrush", Color.FromArgb(0x19, 0x00, 0x00, 0x00) },
            { "ControlAltFillColorTertiaryBrush", Color.FromArgb(0x0B, 0xFF, 0xFF, 0xFF) },
            { "ControlAltFillColorQuarternaryBrush", Color.FromArgb(0x12, 0xFF, 0xFF, 0xFF) },
            { "ControlAltFillColorDisabledBrush", Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF) },
            { "ControlOnImageFillColorDefaultBrush", Color.FromArgb(0xB3, 0x1C, 0x1C, 0x1C) },
            { "ControlOnImageFillColorSecondaryBrush", Color.FromArgb(0xFF, 0x1A, 0x1A, 0x1A) },
            { "ControlOnImageFillColorTertiaryBrush", Color.FromArgb(0xFF, 0x13, 0x13, 0x13) },
            { "ControlOnImageFillColorDisabledBrush", Color.FromArgb(0xFF, 0x1E, 0x1E, 0x1E) },
            { "AccentFillColorSelectedTextBackgroundBrush", AccentShade.Default },
            { "AccentFillColorDefaultBrush", AccentShade.Light2 },
            { "AccentFillColorSecondaryBrush", AccentShade.Light2 },
            { "AccentFillColorTertiaryBrush", AccentShade.Light2 },
            { "AccentFillColorDisabledBrush", Color.FromArgb(0x28, 0xFF, 0xFF, 0xFF) },
            { "ControlStrokeColorDefaultBrush", Color.FromArgb(0x12, 0xFF, 0xFF, 0xFF) },
            { "ControlStrokeColorSecondaryBrush", Color.FromArgb(0x18, 0xFF, 0xFF, 0xFF) },
            { "ControlStrokeColorOnAccentDefaultBrush", Color.FromArgb(0x14, 0xFF, 0xFF, 0xFF) },
            { "ControlStrokeColorOnAccentSecondaryBrush", Color.FromArgb(0x23, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorOnAccentTertiaryBrush", Color.FromArgb(0x37, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorOnAccentDisabledBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "ControlStrokeColorForStrongFillWhenOnImageBrush", Color.FromArgb(0x6B, 0x00, 0x00, 0x00) },
            { "CardStrokeColorDefaultBrush", Color.FromArgb(0x19, 0x00, 0x00, 0x00) },
            { "CardStrokeColorDefaultSolidBrush", Color.FromArgb(0xFF, 0x1C, 0x1C, 0x1C) },
            { "ControlStrongStrokeColorDefaultBrush", Color.FromArgb(0x8B, 0xFF, 0xFF, 0xFF) },
            { "ControlStrongStrokeColorDisabledBrush", Color.FromArgb(0x28, 0xFF, 0xFF, 0xFF) },
            { "SurfaceStrokeColorDefaultBrush", Color.FromArgb(0x15, 0xFF, 0xFF, 0xFF) },
            { "SurfaceStrokeColorFlyoutBrush", Color.FromArgb(0x33, 0x00, 0x00, 0x00) },
            { "SurfaceStrokeColorInverseBrush", Color.FromArgb(0x0F, 0x00, 0x00, 0x00) },
            { "DividerStrokeColorDefaultBrush", Color.FromArgb(0x15, 0xFF, 0xFF, 0xFF) },
            { "FocusStrokeColorOuterBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "FocusStrokeColorInnerBrush", Color.FromArgb(0xB3, 0x00, 0x00, 0x00) },
            { "CardBackgroundFillColorDefaultBrush", Color.FromArgb(0x0D, 0xFF, 0xFF, 0xFF) },
            { "CardBackgroundFillColorSecondaryBrush", Color.FromArgb(0x08, 0xFF, 0xFF, 0xFF) },
            { "SmokeFillColorDefaultBrush", Color.FromArgb(0x33, 0x2C, 0x2C, 0x2C) },
            { "LayerFillColorDefaultBrush", Color.FromArgb(0x09, 0xFF, 0xFF, 0xFF) },
            { "LayerFillColorAltBrush", Color.FromArgb(0x0D, 0xFF, 0xFF, 0xFF) },
            { "LayerOnAcrylicFillColorDefaultBrush", Color.FromArgb(0x09, 0xFF, 0xFF, 0xFF) },
            { "LayerOnAccentAcrylicFillColorDefaultBrush", Color.FromArgb(0x09, 0xFF, 0xFF, 0xFF) },
            { "SolidBackgroundFillColorBaseBrush", Color.FromArgb(0xFF, 0x20, 0x20, 0x20) },
            { "SolidBackgroundFillColorSecondaryBrush", Color.FromArgb(0xFF, 0x1C, 0x1C, 0x1C) },
            { "SolidBackgroundFillColorTertiaryBrush", Color.FromArgb(0xFF, 0x28, 0x28, 0x28) },
            { "SolidBackgroundFillColorQuarternaryBrush", Color.FromArgb(0xFF, 0x2C, 0x2C, 0x2C) },
            { "SystemFillColorAttentionBrush", AccentShade.Light2 },
            { "SystemFillColorSuccessBrush", Color.FromArgb(0xFF, 0x6C, 0xCB, 0x5F) },
            { "SystemFillColorCautionBrush", Color.FromArgb(0xFF, 0xFC, 0xE1, 0x00) },
            { "SystemFillColorCriticalBrush", Color.FromArgb(0xFF, 0xFF, 0x99, 0xA4) },
            { "SystemFillColorNeutralBrush", Color.FromArgb(0x8B, 0xFF, 0xFF, 0xFF) },
            { "SystemFillColorAttentionBackgroundBrush", Color.FromArgb(0x08, 0xFF, 0xFF, 0xFF) },
            { "SystemFillColorSuccessBackgroundBrush", Color.FromArgb(0xFF, 0x39, 0x3D, 0x1B) },
            { "SystemFillColorCautionBackgroundBrush", Color.FromArgb(0xFF, 0x43, 0x35, 0x19) },
            { "SystemFillColorCriticalBackgroundBrush", Color.FromArgb(0xFF, 0x44, 0x27, 0x26) },
            { "SystemFillColorNeutralBackgroundBrush", Color.FromArgb(0x08, 0xFF, 0xFF, 0xFF) },
            { "SystemColorWindowTextColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorWindowColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorButtonFaceColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorButtonTextColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorHighlightColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorHighlightTextColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorHotlightColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "SystemColorGrayTextColorBrush", Color.FromArgb(0xFF, 0xFF, 0x00, 0xFF) },
            { "TextOnAccentFillColorDefaultBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextOnAccentAAFillColorPrimaryBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "TextOnAccentAAFillColorSecondaryBrush", Color.FromArgb(0x80, 0x00, 0x00, 0x00) },
            { "TextOnAccentAAFillColorDisabledBrush", Color.FromArgb(0x87, 0xFF, 0xFF, 0xFF) },
            { "ControlAAFillColorDefaultBrush", Color.FromArgb(0x8B, 0xFF, 0xFF, 0xFF) },
            { "ControlAAFillColorDisabledBrush", Color.FromArgb(0x3F, 0xFF, 0xFF, 0xFF) },
            { "AccentAAFillColorDefaultBrush", AccentShade.Light2 },
            { "AccentAAFillColorSecondaryBrush", AccentShade.Light3 },
            { "AccentAAFillColorTertiaryBrush", AccentShade.Light1 },
            { "AccentAAFillColorDisabledBrush", Color.FromArgb(0x28, 0xFF, 0xFF, 0xFF) },
            { "ControlStrokeColorForAAFillOnImageBrush", Color.FromArgb(0x6B, 0x00, 0x00, 0x00) },
            { "ControlAAStrokeColorDefaultBrush", Color.FromArgb(0x8B, 0xFF, 0xFF, 0xFF) },
            { "ControlAAStrokeColorDisabledBrush", Color.FromArgb(0x28, 0xFF, 0xFF, 0xFF) },
            { "MenuFlyoutItemFocusedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x21, 0x21, 0x21) },
            { "MenuFlyoutItemFocusedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "MenuFlyoutItemDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "MenuFlyoutItemPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x21, 0x21, 0x21) },
            { "MenuFlyoutItemPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "MenuFlyoutItemPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "MenuFlyoutItemPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "MenuFlyoutSeparatorThemeBrush", Color.FromArgb(0xFF, 0x7A, 0x7A, 0x7A) },
            { "SystemControlTransientBorderBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ProgressBarBackgroundThemeBrush", Color.FromArgb(0x59, 0xFF, 0xFF, 0xFF) },
            { "ProgressBarForegroundThemeBrush", Color.FromArgb(0xFF, 0x5B, 0x2E, 0xC5) },
            { "ProgressBarIndeterminateForegroundThemeBrush", Color.FromArgb(0xFF, 0x8A, 0x57, 0xFF) },
            { "ContentDialogBorderThemeBrush", AccentShade.Default },
            { "ContentDialogDimmingThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "InkToolbarFlyoutItemBorderSelectedThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonBackgroundThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonBorderThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonContentDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonContentForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonDisabledBorderThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "RadioButtonForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RadioButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xDE, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonPointerOverBorderThemeBrush", Color.FromArgb(0xDE, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RadioButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonPressedBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "RadioButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonCheckedBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonCheckedDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonCheckedDisabledForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "AppBarToggleButtonCheckedPointerOverBackgroundThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonCheckedPointerOverBorderThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonCheckedPressedBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonCheckedPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "AppBarToggleButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0x21, 0xFF, 0xFF, 0xFF) },
            { "ListBoxBackgroundThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "ListBoxDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ListBoxFocusBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListBoxForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ListBoxItemDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ListBoxItemPointerOverBackgroundThemeBrush", Color.FromArgb(0x21, 0x00, 0x00, 0x00) },
            { "ListBoxItemPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ListBoxItemPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xD3, 0xD3, 0xD3) },
            { "ListBoxItemPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ListBoxItemSelectedDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ListBoxItemSelectedDisabledForegroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ListBoxItemSelectedPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
            { "ToggleSwitchCurtainBackgroundThemeBrush", Color.FromArgb(0xFF, 0x57, 0x29, 0xC1) },
            { "ToggleSwitchCurtainPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x6E, 0x46, 0xCA) },
            { "ToggleSwitchCurtainPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x7E, 0x4F, 0xEC) },
            { "ToggleSwitchDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchHeaderDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchOuterBorderBorderThemeBrush", Color.FromArgb(0x59, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchOuterBorderDisabledBorderThemeBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchThumbBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchThumbBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchThumbDisabledBackgroundThemeBrush", Color.FromArgb(0xFF, 0x7E, 0x7E, 0x7E) },
            { "ToggleSwitchThumbDisabledBorderThemeBrush", Color.FromArgb(0xFF, 0x7E, 0x7E, 0x7E) },
            { "ToggleSwitchThumbPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchThumbPointerOverBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchThumbPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchThumbPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchTrackBackgroundThemeBrush", Color.FromArgb(0x42, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchTrackDisabledBackgroundThemeBrush", Color.FromArgb(0x1F, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchTrackPointerOverBackgroundThemeBrush", Color.FromArgb(0x4A, 0xFF, 0xFF, 0xFF) },
            { "ToggleSwitchTrackPressedBackgroundThemeBrush", Color.FromArgb(0x59, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemCheckHintThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemCheckSelectingThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemCheckThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemDragBackgroundThemeBrush", Color.FromArgb(0x99, 0x46, 0x17, 0xB4) },
            { "ListViewItemFocusBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemOverlayBackgroundThemeBrush", Color.FromArgb(0xA6, 0x00, 0x00, 0x00) },
            { "ListViewItemOverlayForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemOverlaySecondaryForegroundThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemPlaceholderBackgroundThemeBrush", Color.FromArgb(0xFF, 0x3D, 0x3D, 0x3D) },
            { "ListViewItemPointerOverBackgroundThemeBrush", Color.FromArgb(0x4D, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemSelectedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ListViewItemSelectedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ListViewItemSelectedPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
            { "ListViewItemSelectedPointerOverBorderThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
            { "TextBoxForegroundHeaderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextBoxPlaceholderTextThemeBrush", Color.FromArgb(0xAB, 0x00, 0x00, 0x00) },
            { "TextBoxBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextBoxBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextBoxButtonForegroundThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "TextBoxButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xDE, 0xDE, 0xDE) },
            { "TextBoxButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "TextBoxButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "TextBoxButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TextBoxDisabledBorderThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "TextBoxDisabledForegroundThemeBrush", Color.FromArgb(0xFF, 0x66, 0x66, 0x66) },
            { "TextBoxForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ButtonBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ButtonDisabledBorderThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ButtonDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ButtonForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0x21, 0xFF, 0xFF, 0xFF) },
            { "ButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonCheckedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonCheckedBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonCheckedDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonCheckedDisabledForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonCheckedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToggleButtonCheckedPointerOverBackgroundThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonCheckedPointerOverBorderThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonCheckedPressedBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonCheckedPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonDisabledBorderThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0x21, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToggleButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "RepeatButtonBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "RepeatButtonDisabledBorderThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "RepeatButtonDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "RepeatButtonForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "RepeatButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0x21, 0xFF, 0xFF, 0xFF) },
            { "RepeatButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "RepeatButtonPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "RepeatButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "CheckBoxBackgroundThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxBorderThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxContentDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxContentForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxDisabledBackgroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxDisabledBorderThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "CheckBoxForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "CheckBoxPointerOverBackgroundThemeBrush", Color.FromArgb(0xDE, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxPointerOverBorderThemeBrush", Color.FromArgb(0xDE, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "CheckBoxPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxPressedBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "CheckBoxPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "DatePickerHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "DatePickerForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "FlipViewButtonBackgroundThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "FlipViewButtonBorderThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "FlipViewButtonForegroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "FlipViewButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xF0, 0xD7, 0xD7, 0xD7) },
            { "FlipViewButtonPointerOverBorderThemeBrush", Color.FromArgb(0x9E, 0xC1, 0xC1, 0xC1) },
            { "FlipViewButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "FlipViewButtonPressedBackgroundThemeBrush", Color.FromArgb(0xBD, 0x29, 0x29, 0x29) },
            { "FlipViewButtonPressedBorderThemeBrush", Color.FromArgb(0xBD, 0x29, 0x29, 0x29) },
            { "FlipViewButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "PivotForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "PivotHeaderForegroundSelectedBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "PivotHeaderForegroundUnselectedBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "PivotNavButtonBackgroundThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "PivotNavButtonBorderThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "PivotNavButtonForegroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "PivotNavButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xF0, 0xD7, 0xD7, 0xD7) },
            { "PivotNavButtonPointerOverBorderThemeBrush", Color.FromArgb(0x9E, 0xC1, 0xC1, 0xC1) },
            { "PivotNavButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "PivotNavButtonPressedBackgroundThemeBrush", Color.FromArgb(0xBD, 0x29, 0x29, 0x29) },
            { "PivotNavButtonPressedBorderThemeBrush", Color.FromArgb(0xBD, 0x29, 0x29, 0x29) },
            { "PivotNavButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ScrollBarButtonForegroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ScrollBarButtonPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xDA, 0xDA, 0xDA) },
            { "ScrollBarButtonPointerOverBorderThemeBrush", Color.FromArgb(0xFF, 0xDA, 0xDA, 0xDA) },
            { "ScrollBarButtonPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ScrollBarButtonPressedBackgroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ScrollBarButtonPressedBorderThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ScrollBarButtonPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ScrollBarPanningBackgroundThemeBrush", Color.FromArgb(0xFF, 0xCD, 0xCD, 0xCD) },
            { "ScrollBarPanningBorderThemeBrush", Color.FromArgb(0x7D, 0x9A, 0x9A, 0x9A) },
            { "ScrollBarThumbBackgroundThemeBrush", Color.FromArgb(0xFF, 0xCD, 0xCD, 0xCD) },
            { "ScrollBarThumbBorderThemeBrush", Color.FromArgb(0x3B, 0x55, 0x55, 0x55) },
            { "ScrollBarThumbPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xDA, 0xDA, 0xDA) },
            { "ScrollBarThumbPointerOverBorderThemeBrush", Color.FromArgb(0x6B, 0xB7, 0xB7, 0xB7) },
            { "ScrollBarThumbPressedBackgroundThemeBrush", Color.FromArgb(0x99, 0x00, 0x00, 0x00) },
            { "ScrollBarThumbPressedBorderThemeBrush", Color.FromArgb(0xED, 0x55, 0x55, 0x55) },
            { "ScrollBarTrackBackgroundThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "ScrollBarTrackBorderThemeBrush", Color.FromArgb(0x59, 0xD5, 0xD5, 0xD5) },
            { "SliderThumbBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbDisabledBackgroundThemeBrush", Color.FromArgb(0xFF, 0x7E, 0x7E, 0x7E) },
            { "SliderThumbPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbPointerOverBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderThumbPressedBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "SliderTickmarkOutsideBackgroundThemeBrush", Color.FromArgb(0x80, 0xFF, 0xFF, 0xFF) },
            { "SliderTickMarkOutsideDisabledForegroundThemeBrush", Color.FromArgb(0x80, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackBackgroundThemeBrush", Color.FromArgb(0x29, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackDecreaseBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5B, 0x2E, 0xC5) },
            { "SliderTrackDecreaseDisabledBackgroundThemeBrush", Color.FromArgb(0x1F, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackDecreasePointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x72, 0x4B, 0xCD) },
            { "SliderTrackDecreasePressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x81, 0x52, 0xEF) },
            { "SliderTrackDisabledBackgroundThemeBrush", Color.FromArgb(0x29, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackPointerOverBackgroundThemeBrush", Color.FromArgb(0x46, 0xFF, 0xFF, 0xFF) },
            { "SliderTrackPressedBackgroundThemeBrush", Color.FromArgb(0x59, 0xFF, 0xFF, 0xFF) },
            { "SliderHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TimePickerHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "TimePickerForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ToolTipBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ToolTipBorderThemeBrush", Color.FromArgb(0xFF, 0x80, 0x80, 0x80) },
            { "ToolTipForegroundThemeBrush", Color.FromArgb(0xFF, 0x66, 0x66, 0x66) },
            { "PersonPictureForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "PersonPictureEllipseBadgeForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "PersonPictureEllipseBadgeFillThemeBrush", Color.FromArgb(0xFF, 0x33, 0x33, 0x33) },
            { "PersonPictureEllipseBadgeStrokeThemeBrush", Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF) },
            { "PersonPictureEllipseFillThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "TeachingTipTopHighlightBrush", Color.FromArgb(0x0D, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxArrowDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxArrowForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxArrowPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxBackgroundThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxBorderThemeBrush", Color.FromArgb(0xCC, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxDisabledBorderThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxHeaderForegroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxItemDisabledForegroundThemeBrush", Color.FromArgb(0x66, 0x00, 0x00, 0x00) },
            { "ComboBoxItemPointerOverBackgroundThemeBrush", Color.FromArgb(0x21, 0x00, 0x00, 0x00) },
            { "ComboBoxItemPointerOverForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxItemPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xD3, 0xD3, 0xD3) },
            { "ComboBoxItemPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxItemSelectedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ComboBoxItemSelectedDisabledBackgroundThemeBrush", Color.FromArgb(0x8C, 0x00, 0x00, 0x00) },
            { "ComboBoxItemSelectedDisabledForegroundThemeBrush", Color.FromArgb(0x99, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxItemSelectedPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
            { "ComboBoxPlaceholderTextForegroundThemeBrush", Color.FromArgb(0x88, 0x00, 0x00, 0x00) },
            { "ComboBoxPointerOverBackgroundThemeBrush", Color.FromArgb(0xDE, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxPointerOverBorderThemeBrush", Color.FromArgb(0xDE, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxPopupBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxPopupBorderThemeBrush", Color.FromArgb(0xFF, 0x21, 0x21, 0x21) },
            { "ComboBoxPopupForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxPressedBackgroundThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxPressedBorderThemeBrush", Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF) },
            { "ComboBoxPressedHighlightThemeBrush", Color.FromArgb(0xFF, 0xD3, 0xD3, 0xD3) },
            { "ComboBoxPressedForegroundThemeBrush", Color.FromArgb(0xFF, 0x00, 0x00, 0x00) },
            { "ComboBoxSelectedBackgroundThemeBrush", Color.FromArgb(0xFF, 0x46, 0x17, 0xB4) },
            { "ComboBoxSelectedPointerOverBackgroundThemeBrush", Color.FromArgb(0xFF, 0x5F, 0x37, 0xBE) },
        };
    }
}
