// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLPhoneCallDiscardReasonMissed : TLPhoneCallDiscardReasonBase 
	{
		public TLPhoneCallDiscardReasonMissed() { }
		public TLPhoneCallDiscardReasonMissed(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhoneCallDiscardReasonMissed; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x85E42301);
		}
	}
}