// <auto-generated/>
using System;

namespace Telegram.Api.TL
{
	public partial class TLUpdateBotCallbackQuery : TLUpdateBase 
	{
		[Flags]
		public enum Flag : Int32
		{
			Data = (1 << 0),
			GameShortName = (1 << 1),
		}

		public bool HasData { get { return Flags.HasFlag(Flag.Data); } set { Flags = value ? (Flags | Flag.Data) : (Flags & ~Flag.Data); } }
		public bool HasGameShortName { get { return Flags.HasFlag(Flag.GameShortName); } set { Flags = value ? (Flags | Flag.GameShortName) : (Flags & ~Flag.GameShortName); } }

		public Flag Flags { get; set; }
		public Int64 QueryId { get; set; }
		public Int32 UserId { get; set; }
		public TLPeerBase Peer { get; set; }
		public Int32 MsgId { get; set; }
		public Int64 ChatInstance { get; set; }
		public Byte[] Data { get; set; }
		public String GameShortName { get; set; }

		public TLUpdateBotCallbackQuery() { }
		public TLUpdateBotCallbackQuery(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateBotCallbackQuery; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (Flag)from.ReadInt32();
			QueryId = from.ReadInt64();
			UserId = from.ReadInt32();
			Peer = TLFactory.Read<TLPeerBase>(from);
			MsgId = from.ReadInt32();
			ChatInstance = from.ReadInt64();
			if (HasData) Data = from.ReadByteArray();
			if (HasGameShortName) GameShortName = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			UpdateFlags();

			to.Write(0xE73547E1);
			to.Write((Int32)Flags);
			to.Write(QueryId);
			to.Write(UserId);
			to.WriteObject(Peer);
			to.Write(MsgId);
			to.Write(ChatInstance);
			if (HasData) to.WriteByteArray(Data);
			if (HasGameShortName) to.Write(GameShortName);
		}

		private void UpdateFlags()
		{
			HasData = Data != null;
			HasGameShortName = GameShortName != null;
		}
	}
}