// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL.Updates.Methods
{
	/// <summary>
	/// RCP method updates.getState.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesState"/>
	/// </summary>
	public partial class TLUpdatesGetState : TLObject
	{
		public TLUpdatesGetState() { }
		public TLUpdatesGetState(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdatesGetState; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
		}
	}
}