//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 11/11/2017 21:22:01
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Unigram.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public sealed partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Forever"
        /// </summary>
        public static string UserRestrictionsUntilForever
        {
            get
            {
                return resourceLoader.GetString("UserRestrictionsUntilForever");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The app will be closed. Relaunch it to login again."
        /// </summary>
        public static string TGLogoutSucceededDialogText
        {
            get
            {
                return resourceLoader.GetString("TGLogoutSucceededDialogText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Are you sure you want to logout?"
        /// </summary>
        public static string TGLogoutText
        {
            get
            {
                return resourceLoader.GetString("TGLogoutText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Please note that Telegram Support is done by volunteers. We try to respond as quickly as possible, but it may take a while. Please take a look at the Telegram FAQ: it has important troubleshooting tips and answers to most questions."
        /// </summary>
        public static string TGSupportDisclaimerDetails
        {
            get
            {
                return resourceLoader.GetString("TGSupportDisclaimerDetails");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "FAQ"
        /// </summary>
        public static string TGSupportDisclaimerPrimaryText
        {
            get
            {
                return resourceLoader.GetString("TGSupportDisclaimerPrimaryText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Are you sure?"
        /// </summary>
        public static string UnblockUserConfirmationDialogText
        {
            get
            {
                return resourceLoader.GetString("UnblockUserConfirmationDialogText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Unblock?"
        /// </summary>
        public static string UnblockUserConfirmationDialogTitle
        {
            get
            {
                return resourceLoader.GetString("UnblockUserConfirmationDialogTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "When using mobile data"
        /// </summary>
        public static string WhenOnMobileData
        {
            get
            {
                return resourceLoader.GetString("WhenOnMobileData");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "When connected to Wi-Fi"
        /// </summary>
        public static string WhenOnWiFi
        {
            get
            {
                return resourceLoader.GetString("WhenOnWiFi");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "When roaming"
        /// </summary>
        public static string WhenRoaming
        {
            get
            {
                return resourceLoader.GetString("WhenRoaming");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Proxy Settings"
        /// </summary>
        public static string ProxySettingsShareTitle
        {
            get
            {
                return resourceLoader.GetString("ProxySettingsShareTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Audio messages"
        /// </summary>
        public static string AutoDownload_Audio
        {
            get
            {
                return resourceLoader.GetString("AutoDownload_Audio");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Files"
        /// </summary>
        public static string AutoDownload_Document
        {
            get
            {
                return resourceLoader.GetString("AutoDownload_Document");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "GIFs"
        /// </summary>
        public static string AutoDownload_GIF
        {
            get
            {
                return resourceLoader.GetString("AutoDownload_GIF");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Music"
        /// </summary>
        public static string AutoDownload_Music
        {
            get
            {
                return resourceLoader.GetString("AutoDownload_Music");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No media"
        /// </summary>
        public static string AutoDownload_None
        {
            get
            {
                return resourceLoader.GetString("AutoDownload_None");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Photos"
        /// </summary>
        public static string AutoDownload_Photo
        {
            get
            {
                return resourceLoader.GetString("AutoDownload_Photo");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Video messages"
        /// </summary>
        public static string AutoDownload_Round
        {
            get
            {
                return resourceLoader.GetString("AutoDownload_Round");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Videos"
        /// </summary>
        public static string AutoDownload_Video
        {
            get
            {
                return resourceLoader.GetString("AutoDownload_Video");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reset all notifications?"
        /// </summary>
        public static string ResetNotificationsDialogBody
        {
            get
            {
                return resourceLoader.GetString("ResetNotificationsDialogBody");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Confirm"
        /// </summary>
        public static string ResetNotificationsDialogTitle
        {
            get
            {
                return resourceLoader.GetString("ResetNotificationsDialogTitle");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Edit permissions"
        /// </summary>
        public static string ParticipantEdit
        {
            get
            {
                return resourceLoader.GetString("ParticipantEdit");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Promote"
        /// </summary>
        public static string ParticipantPromote
        {
            get
            {
                return resourceLoader.GetString("ParticipantPromote");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Restrict"
        /// </summary>
        public static string ParticipantRestrict
        {
            get
            {
                return resourceLoader.GetString("ParticipantRestrict");
            }
        }
    }
}
