// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL.Account.Methods
{
	/// <summary>
	/// RCP method account.updateUsername.
	/// Returns <see cref="Telegram.Api.TL.TLUserBase"/>
	/// </summary>
	public partial class TLAccountUpdateUsername : TLObject
	{
		public String Username { get; set; }

		public TLAccountUpdateUsername() { }
		public TLAccountUpdateUsername(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountUpdateUsername; } }

		public override void Read(TLBinaryReader from)
		{
			Username = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteString(Username ?? string.Empty);
		}
	}
}