// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL.Updates
{
	public partial class TLUpdatesState : TLObject 
	{
		public Int32 Pts { get; set; }
		public Int32 Qts { get; set; }
		public Int32 Date { get; set; }
		public Int32 Seq { get; set; }
		public Int32 UnreadCount { get; set; }

		public TLUpdatesState() { }
		public TLUpdatesState(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdatesState; } }

		public override void Read(TLBinaryReader from)
		{
			Pts = from.ReadInt32();
			Qts = from.ReadInt32();
			Date = from.ReadInt32();
			Seq = from.ReadInt32();
			UnreadCount = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(Pts);
			to.WriteInt32(Qts);
			to.WriteInt32(Date);
			to.WriteInt32(Seq);
			to.WriteInt32(UnreadCount);
		}
	}
}