//
// Copyright (c) Fela Ameghino 2015-2026
//
// Distributed under the GNU General Public License v3.0. (See accompanying
// file LICENSE or copy at https://www.gnu.org/licenses/gpl-3.0.txt)
//

using System;

namespace Telegram.Services
{
    // The registrations SessionResolverGenerator turns into the fields, the constructor and the
    // Resolve<T> switch. Adding a view model here is all that is needed to make it resolvable.
    //
    // Singletons and Lazy are read pairwise, interface then implementation. Order matters only in
    // that the generator sorts singletons by dependency and promotes any lazy one they need.
    [GenerateResolver(
        Self = new Type[]
        {
            typeof(ISession),
        },
        // The one global Resolve hands out; the other four are constructor-only.
        Exposed = new Type[]
        {
            typeof(IShortcutsService),
        },
        Globals = new Type[]
        {
            typeof(Telegram.Services.ILifetimeService),
            typeof(Telegram.Services.ILocaleService),
            typeof(Telegram.Services.IPasscodeService),
            typeof(Telegram.Services.IShortcutsService),
            typeof(Telegram.Services.IProxyService),
        },
        Singletons = new Type[]
        {
            typeof(Telegram.Services.IDeviceInfoService), typeof(Telegram.Services.DeviceInfoService),
            typeof(Telegram.Services.ISettingsService), typeof(Telegram.Services.SettingsService),
            typeof(Telegram.Services.IEventAggregator), typeof(Telegram.Services.EventAggregator),
            typeof(Telegram.Services.IClientService), typeof(Telegram.Services.ClientService),
            typeof(Telegram.Services.IContactsService), typeof(Telegram.Services.ContactsService),
            typeof(Telegram.Services.IVoipService), typeof(Telegram.Services.VoipService),
            typeof(Telegram.Services.INetworkService), typeof(Telegram.Services.NetworkService),
            typeof(Telegram.Services.IGenerationService), typeof(Telegram.Services.GenerationService),
            typeof(Telegram.Services.INotificationsService), typeof(Telegram.Services.NotificationsService),
        },
        Lazy = new Type[]
        {
            typeof(Telegram.Services.ISettingsSearchService), typeof(Telegram.Services.SettingsSearchService),
            typeof(Telegram.Services.ICloudUpdateService), typeof(Telegram.Services.CloudUpdateService),
            typeof(Telegram.Services.ILocationService), typeof(Telegram.Services.LocationService),
            typeof(Telegram.Services.IThemeService), typeof(Telegram.Services.ThemeService),
            typeof(Telegram.Services.IViewService), typeof(Telegram.Services.ViewService),
            typeof(Telegram.Services.IStorageService), typeof(Telegram.Services.StorageService),
            typeof(Telegram.Services.ITranslateService), typeof(Telegram.Services.TranslateService),
            typeof(Telegram.Services.IProfilePhotoService), typeof(Telegram.Services.ProfilePhotoService),
            typeof(Telegram.Services.ITextRecognitionService), typeof(Telegram.Services.TextRecognitionService),
        },
        Instances = new Type[]
        {
            typeof(Telegram.ViewModels.Authorization.AuthorizationViewModel),
            typeof(Telegram.ViewModels.Authorization.AuthorizationRegistrationViewModel),
            typeof(Telegram.ViewModels.Authorization.AuthorizationCodeViewModel),
            typeof(Telegram.ViewModels.Authorization.AuthorizationPasswordViewModel),
            typeof(Telegram.ViewModels.Authorization.AuthorizationRecoveryViewModel),
            typeof(Telegram.ViewModels.Authorization.AuthorizationEmailAddressViewModel),
            typeof(Telegram.ViewModels.Authorization.AuthorizationEmailCodeViewModel),
            typeof(Telegram.ViewModels.MainViewModel),
            typeof(Telegram.ViewModels.ContactsViewModel),
            typeof(Telegram.ViewModels.CallsViewModel),
            typeof(Telegram.ViewModels.ChooseChatsViewModel),
            typeof(Telegram.ViewModels.SendLocationViewModel),
            typeof(Telegram.ViewModels.DialogViewModel),
            typeof(Telegram.ViewModels.DialogBusinessRepliesViewModel),
            typeof(Telegram.ViewModels.DialogWelcomeMessagesViewModel),
            typeof(Telegram.ViewModels.DialogPinnedViewModel),
            typeof(Telegram.ViewModels.DialogScheduledViewModel),
            typeof(Telegram.ViewModels.DialogEventLogViewModel),
            typeof(Telegram.ViewModels.Drawers.AnimationDrawerViewModel),
            typeof(Telegram.ViewModels.Drawers.StickerDrawerViewModel),
            typeof(Telegram.ViewModels.Drawers.EmojiDrawerViewModel),
            typeof(Telegram.ViewModels.Drawers.EffectDrawerViewModel),
            typeof(Telegram.ViewModels.CreateChatPhotoViewModel),
            typeof(Telegram.ViewModels.ProfileViewModel),
            typeof(Telegram.ViewModels.Profile.ProfileStoriesTabViewModel),
            typeof(Telegram.ViewModels.Profile.ProfileMembersTabViewModel),
            typeof(Telegram.ViewModels.Profile.ProfileGroupsTabViewModel),
            typeof(Telegram.ViewModels.Profile.ProfileChannelsTabViewModel),
            typeof(Telegram.ViewModels.Profile.ProfileBotsTabViewModel),
            typeof(Telegram.ViewModels.Profile.ProfileGiftsTabViewModel),
            typeof(Telegram.ViewModels.Profile.ProfileSavedChatsTabViewModel),
            typeof(Telegram.ViewModels.Profile.ProfileTopicsTabViewModel),
            typeof(Telegram.ViewModels.Users.UserEditViewModel),
            typeof(Telegram.ViewModels.Users.UserAffiliateViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupEditViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupEditTypeViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupEditStickerSetViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupEditAdministratorViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupEditRestrictedViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupEditLinkedChatViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupChooseMemberViewModel),
            typeof(Telegram.ViewModels.Chats.ChatInviteLinksViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupAdministratorsViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupBannedViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupPermissionsViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupTopicsViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupDirectMessagesViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupMembersViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupReactionsViewModel),
            typeof(Telegram.ViewModels.Chats.ChatStatisticsViewModel),
            typeof(Telegram.ViewModels.Chats.ChatBoostsViewModel),
            typeof(Telegram.ViewModels.Chats.ChatRevenueViewModel),
            typeof(Telegram.ViewModels.Chats.ChatStarsViewModel),
            typeof(Telegram.ViewModels.Chats.ChatAffiliateViewModel),
            typeof(Telegram.ViewModels.Chats.MessageStatisticsViewModel),
            typeof(Telegram.ViewModels.Create.NewContactViewModel),
            typeof(Telegram.ViewModels.Create.NewChannelViewModel),
            typeof(Telegram.ViewModels.Create.NewGroupViewModel),
            typeof(Telegram.ViewModels.Create.NewBotViewModel),
            typeof(Telegram.ViewModels.InstantViewModel),
            typeof(Telegram.ViewModels.LogOutViewModel),
            typeof(Telegram.ViewModels.DiagnosticsViewModel),
            typeof(Telegram.ViewModels.Chats.ChatStoriesViewModel),
            typeof(Telegram.ViewModels.SettingsViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsAdvancedViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsStorageViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsNetworkViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsUsernameViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsSessionsViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsWebSessionsViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsBlockedChatsViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsNotificationsViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsNotificationsExceptionsViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsDataAndStorageViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsProxyViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsPrivacyAndSecurityViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyAllowCallsViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyAllowP2PCallsViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyAllowChatInvitesViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyShowForwardedViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyPhoneViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyShowPhoneViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyAutosaveGiftsViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyAllowFindingByPhoneNumberViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyAllowPrivateVoiceAndVideoNoteMessagesViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyShowPhotoViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyShowProfileAudioViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyShowStatusViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyShowBioViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyShowBirthdateViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyAllowUnpaidMessagesViewModel),
            typeof(Telegram.ViewModels.Settings.Privacy.SettingsPrivacyNewChatViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsAutoDeleteViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsProfileViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsProfileColorViewModel),
            typeof(Telegram.ViewModels.Supergroups.SupergroupProfileColorViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsPasswordViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsPasskeysViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsPasscodeViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsStickersViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsLanguageViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsAppearanceViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsThemesViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsThemeViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsNightModeViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsBackgroundsViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsShortcutsViewModel),
            typeof(Telegram.ViewModels.Settings.SettingsPowerSavingViewModel),
            typeof(Telegram.ViewModels.BackgroundViewModel),
            typeof(Telegram.ViewModels.StickersViewModel),
            typeof(Telegram.ViewModels.Payments.PaymentAddressViewModel),
            typeof(Telegram.ViewModels.Payments.PaymentCredentialsViewModel),
            typeof(Telegram.ViewModels.Payments.PaymentFormViewModel),
            typeof(Telegram.ViewModels.StoryInteractionsViewModel),
            typeof(Telegram.ViewModels.Folders.FoldersViewModel),
            typeof(Telegram.ViewModels.Folders.FolderViewModel),
            typeof(Telegram.ViewModels.Folders.ShareFolderViewModel),
            typeof(Telegram.ViewModels.Folders.AddFolderViewModel),
            typeof(Telegram.ViewModels.Folders.RemoveFolderViewModel),
            typeof(Telegram.ViewModels.DownloadsViewModel),
            typeof(Telegram.ViewModels.ChooseSoundViewModel),
            typeof(Telegram.ViewModels.ChatNotificationsViewModel),
            typeof(Telegram.ViewModels.Premium.PromoViewModel),
            typeof(Telegram.ViewModels.Stars.StarsViewModel),
            typeof(Telegram.ViewModels.Stars.BuyViewModel),
            typeof(Telegram.ViewModels.Stars.PayViewModel),
            typeof(Telegram.ViewModels.Business.BusinessViewModel),
            typeof(Telegram.ViewModels.Business.BusinessLocationViewModel),
            typeof(Telegram.ViewModels.Business.BusinessHoursViewModel),
            typeof(Telegram.ViewModels.Business.BusinessRepliesViewModel),
            typeof(Telegram.ViewModels.Business.BusinessGreetViewModel),
            typeof(Telegram.ViewModels.Business.BusinessAwayViewModel),
            typeof(Telegram.ViewModels.Business.BusinessBotsViewModel),
            typeof(Telegram.ViewModels.Business.BusinessIntroViewModel),
            typeof(Telegram.ViewModels.Business.BusinessChatLinksViewModel),
            typeof(Telegram.ViewModels.RevenueViewModel),
        })]
    public partial class SessionImpl
    {
    }
}
