// <auto-generated/>
using System;


namespace Telegram.Api.TL.Account
{
	public partial class TLAccountPassword : TLAccountPasswordBase 
	{
		public Byte[] CurrentSalt { get; set; }
		public String Hint { get; set; }
		public Boolean HasRecovery { get; set; }

		public TLAccountPassword() { }

		

	}
}