// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLBotInfo : TLObject 
	{
		public Int32 UserId { get; set; }
		public String Description { get; set; }
		public TLVector<TLBotCommand> Commands { get; set; }

		public TLBotInfo() { }
		public TLBotInfo(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.BotInfo; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
			Description = from.ReadString();
			Commands = TLFactory.Read<TLVector<TLBotCommand>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(UserId);
			to.WriteString(Description ?? string.Empty);
			to.WriteObject(Commands);
		}
	}
}