// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLChannelRoleEditor : TLChannelParticipantRoleBase 
	{
		public TLChannelRoleEditor() { }
		public TLChannelRoleEditor(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelRoleEditor; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteUInt32(0x820BFE8C);
		}
	}
}