// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLChatParticipants : TLChatParticipantsBase 
	{
		public TLVector<TLChatParticipantBase> Participants { get; set; }
		public Int32 Version { get; set; }

		public TLChatParticipants() { }
		public TLChatParticipants(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChatParticipants; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
			Participants = TLFactory.Read<TLVector<TLChatParticipantBase>>(from);
			Version = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(ChatId);
			to.WriteObject(Participants);
			to.WriteInt32(Version);
		}
	}
}