// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLHelpNoAppUpdate : TLHelpAppUpdateBase 
	{
		public TLHelpNoAppUpdate() { }
		public TLHelpNoAppUpdate(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpNoAppUpdate; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteUInt32(0xC45A6536);
		}
	}
}