// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLInputMessageEntityMentionName : TLMessageEntityBase 
	{
		public TLInputUserBase UserId { get; set; }

		public TLInputMessageEntityMentionName() { }
		public TLInputMessageEntityMentionName(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputMessageEntityMentionName; } }

		public override void Read(TLBinaryReader from)
		{
			Offset = from.ReadInt32();
			Length = from.ReadInt32();
			UserId = TLFactory.Read<TLInputUserBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteInt32(Offset);
			to.WriteInt32(Length);
			to.WriteObject(UserId);
		}
	}
}