// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLMsgsStateReq : TLObject 
	{
		public TLVector<Int64> MsgIds { get; set; }

		public TLMsgsStateReq() { }
		public TLMsgsStateReq(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MsgsStateReq; } }

		public override void Read(TLBinaryReader from)
		{
			MsgIds = TLFactory.Read<TLVector<Int64>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteObject(MsgIds);
		}
	}
}