// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL
{
	public partial class TLUpdateLangPack : TLUpdateBase 
	{
		public TLLangPackDifference Difference { get; set; }

		public TLUpdateLangPack() { }
		public TLUpdateLangPack(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateLangPack; } }

		public override void Read(TLBinaryReader from)
		{
			Difference = TLFactory.Read<TLLangPackDifference>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteObject(Difference);
		}
	}
}