// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Phone
{
	/// <summary>
	/// RCP method phone.saveCallDebug.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
	public partial class TLPhoneSaveCallDebug : TLObject
	{
		public TLInputPhoneCall Peer { get; set; }
		public TLDataJSON Debug { get; set; }

		public TLPhoneSaveCallDebug() { }
		public TLPhoneSaveCallDebug(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhoneSaveCallDebug; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputPhoneCall>(from);
			Debug = TLFactory.Read<TLDataJSON>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x277ADD7E);
			to.WriteObject(Peer);
			to.WriteObject(Debug);
		}
	}
}