// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Phone
{
	/// <summary>
	/// RCP method phone.acceptCall.
	/// Returns <see cref="Telegram.Api.TL.TLPhonePhoneCall"/>
	/// </summary>
	public partial class TLPhoneAcceptCall : TLObject
	{
		public TLInputPhoneCall Peer { get; set; }
		public Byte[] GB { get; set; }
		public TLPhoneCallProtocol Protocol { get; set; }

		public TLPhoneAcceptCall() { }
		public TLPhoneAcceptCall(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhoneAcceptCall; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputPhoneCall>(from);
			GB = from.ReadByteArray();
			Protocol = TLFactory.Read<TLPhoneCallProtocol>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3BD2B4A0);
			to.WriteObject(Peer);
			to.WriteByteArray(GB);
			to.WriteObject(Protocol);
		}
	}
}