// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Auth
{
	/// <summary>
	/// RCP method auth.sendInvites.
	/// Returns <see cref="Telegram.Api.TL.TLBoolBase"/>
	/// </summary>
	public partial class TLAuthSendInvites : TLObject
	{
		public TLVector<String> PhoneNumbers { get; set; }
		public String Message { get; set; }

		public TLAuthSendInvites() { }
		public TLAuthSendInvites(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AuthSendInvites; } }

		public override void Read(TLBinaryReader from)
		{
			PhoneNumbers = TLFactory.Read<TLVector<String>>(from);
			Message = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x771C1D97);
			to.WriteObject(PhoneNumbers);
			to.Write(Message);
		}
	}
}