// <auto-generated/>
using System;

namespace Telegram.Api.TL.Stickers.Methods
{
	/// <summary>
	/// RCP method stickers.addStickerToSet.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesStickerSet"/>
	/// </summary>
	public partial class TLStickersAddStickerToSet : TLObject
	{
		public TLInputStickerSetBase StickerSet { get; set; }
		public TLInputStickerSetItem Sticker { get; set; }

		public TLStickersAddStickerToSet() { }
		public TLStickersAddStickerToSet(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.StickersAddStickerToSet; } }

		public override void Read(TLBinaryReader from)
		{
			StickerSet = TLFactory.Read<TLInputStickerSetBase>(from);
			Sticker = TLFactory.Read<TLInputStickerSetItem>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x8653FEBE);
			to.WriteObject(StickerSet);
			to.WriteObject(Sticker);
		}
	}
}