// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL.Methods.Contacts
{
	/// <summary>
	/// RCP method contacts.exportCard.
	/// Returns <see cref="Telegram.Api.TL.TLVector<TLint>"/>
	/// </summary>
	public partial class TLContactsExportCard : TLObject
	{
		public TLContactsExportCard() { }
		public TLContactsExportCard(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsExportCard; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteUInt32(0x84E53737);
		}
	}
}