namespace Telegram.Native.Calls
{
    delegate void BroadcastPartRequestedDeferral(Int64 time, Int64 response, Telegram.Td.Api.FilePart filePart);

    [default_interface]
    runtimeclass BroadcastPartRequestedEventArgs
    {
        Int32 Scale{ get; };
        Int64 Time{ get; };
        Int32 ChannelId{ get; };
        Telegram.Td.Api.GroupCallVideoQuality VideoQuality{ get; };
        BroadcastPartRequestedDeferral Deferral{ get; };
    }
}
