import "VoipVideoCapture.idl";

namespace Unigram.Native.Calls
{
    [default_interface]
    runtimeclass VoipScreenCapture : IVoipVideoCapture
    {
        VoipScreenCapture(Windows.Graphics.Capture.GraphicsCaptureItem item);
    }
}
