import "Unigram.Native.Calls.idl";
import "VoipGroupDescriptor.idl";
import "VoipVideoCapture.idl";
import "VoipVideoRendererToken.idl";
import "GroupNetworkStateChangedEventArgs.idl";
import "BroadcastPartRequestedEventArgs.idl";
import "MediaChannelDescriptionsRequestedEventArgs.idl";

namespace Unigram.Native.Calls
{
    delegate void EmitJsonPayloadDelegate(Int32 ssrc, String payload);

    [default_interface]
    runtimeclass VoipGroupManager : Windows.Foundation.IClosable
    {
        VoipGroupManager(VoipGroupDescriptor descriptor);

        void SetConnectionMode(VoipGroupConnectionMode connectionMode, Boolean keepBroadcastIfWasEnabled);

        void EmitJoinPayload(EmitJsonPayloadDelegate completion);
        [default_overload]
        void SetJoinResponsePayload(String payload);
        void RemoveSsrcs(Windows.Foundation.Collections.IVector<Int32> ssrcs);

        VoipVideoRendererToken AddIncomingVideoOutput(String endpointId, Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl canvas);

        Boolean IsMuted;

        void SetAudioOutputDevice(String id);
        void SetAudioInputDevice(String id);
        void SetVideoCapture(VoipVideoCapture videoCapture);

        void SetVolume(Int32 ssrc, Double volume);

        event Windows.Foundation.TypedEventHandler<VoipGroupManager, GroupNetworkStateChangedEventArgs> NetworkStateUpdated;
        event Windows.Foundation.TypedEventHandler<VoipGroupManager, Windows.Foundation.Collections.IMapView<Int32, Windows.Foundation.Collections.IKeyValuePair<Single, Boolean> > > AudioLevelsUpdated;

        event Windows.Foundation.TypedEventHandler<VoipGroupManager, BroadcastPartRequestedEventArgs> BroadcastPartRequested;
        event Windows.Foundation.TypedEventHandler<VoipGroupManager, MediaChannelDescriptionsRequestedEventArgs> MediaChannelDescriptionsRequested;
    }
}
