import "VoipVideoCapture.idl";

namespace Unigram.Native.Calls
{
    runtimeclass VoipScreenCapture : VoipCaptureBase, Windows.Foundation.IClosable
    {
        VoipScreenCapture(Windows.Graphics.Capture.GraphicsCaptureItem item);

        event Windows.Foundation.TypedEventHandler<VoipScreenCapture, IInspectable> FatalErrorOccurred;
        event Windows.Foundation.TypedEventHandler<VoipScreenCapture, Boolean> Paused;
    }
}
