import "Unigram.Native.Calls.idl";
import "VoipVideoCapture.idl";

namespace Unigram.Native.Calls
{
    [default_interface]
    runtimeclass VoipGroupDescriptor 
    {
        VoipGroupDescriptor();

        String AudioInputId;
        String AudioOutputId;
        VoipVideoContentType VideoContentType;
        VoipVideoCapture VideoCapture;

        Boolean IsNoiseSuppressionEnabled;
    }
}
