import "Unigram.Native.Calls.idl";

namespace Unigram.Native.Calls
{
    [default_interface]
    unsealed runtimeclass VoipVideoCapture : Windows.Foundation.IClosable
    {
        VoipVideoCapture(String id);

        void SwitchToDevice(String deviceId);
        void SetPreferredAspectRatio(Single aspectRatio);

        void SetState(VoipVideoState state);
        void SetOutput(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl canvas);
        void SetOutput(Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl canvas, Boolean enableBlur);
    }
} // namespace Unigram.Native.Calls
