//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.1.240821-rc.1+f962c65f63
//       
//       Command:
//           LottieGen -DisableTranslationOptimizer -GenerateColorBindings -Language CSharp -MinimumUapVersion 8 -Namespace Telegram.Assets.Icons -Public -WinUIVersion 2.7 -InputFile ChecklistSelect.json
//       
//       Input file:
//           ChecklistSelect.json (4000 bytes created 23:38+04:00 Jun 26 2025)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ___________________________________________________________
// |       Object stats       | UAP v15 count | UAP v8 count |
// |__________________________|_______________|______________|
// | All CompositionObjects   |           125 |          129 |
// |--------------------------+---------------+--------------|
// | Expression animators     |             5 |            6 |
// | KeyFrame animators       |             2 |            2 |
// | Reference parameters     |             5 |            6 |
// | Expression operations    |            16 |           16 |
// |--------------------------+---------------+--------------|
// | Animated brushes         |             4 |            4 |
// | Animated gradient stops  |             - |            - |
// | ExpressionAnimations     |             5 |            6 |
// | PathKeyFrameAnimations   |             - |            - |
// |--------------------------+---------------+--------------|
// | ContainerVisuals         |             7 |            7 |
// | ShapeVisuals             |             4 |            4 |
// |--------------------------+---------------+--------------|
// | ContainerShapes          |            20 |           20 |
// | CompositionSpriteShapes  |             4 |            4 |
// |--------------------------+---------------+--------------|
// | Brushes                  |             7 |            7 |
// | Gradient stops           |             - |            - |
// | CompositionVisualSurface |             2 |            2 |
// -----------------------------------------------------------
using Microsoft.Graphics.Canvas;
using Microsoft.Graphics.Canvas.Effects;
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace Telegram.Assets.Icons
{
    // Name:        Comp 1
    // Frame rate:  100 fps
    // Frame count: 33
    // Duration:    330.0 mS
    // ___________________________________________________________
    // | Theme property |   Accessor   | Type  |  Default value  |
    // |________________|______________|_______|_________________|
    // | #000000        | Color_000000 | Color | #FF000000 Black |
    // | #FF0000        | Color_FF0000 | Color |  #FFFF0000 Red  |
    // | #FFFFFF        | Color_FFFFFF | Color | #FFFFFFFF White |
    // -----------------------------------------------------------
    public sealed partial class ChecklistSelect
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.333 seconds.
        internal const long c_durationTicks = 2500000;

        // Theme property: Color_000000.
        internal static readonly Color c_themeColor_000000 = Color.FromArgb(0xFF, 0x00, 0x00, 0x00);

        // Theme property: Color_FF0000.
        internal static readonly Color c_themeColor_FF0000 = Color.FromArgb(0xFF, 0xFF, 0x00, 0x00);

        // Theme property: Color_FFFFFF.
        internal static readonly Color c_themeColor_FFFFFF = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF);

        CompositionPropertySet _themeProperties;
        Color _themeColor_000000 = c_themeColor_000000;
        Color _themeColor_FF0000 = c_themeColor_FF0000;
        Color _themeColor_FFFFFF = c_themeColor_FFFFFF;

        // Theme properties.
        public Color Color_000000
        {
            get => _themeColor_000000;
            set
            {
                _themeColor_000000 = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Color_000000", ColorAsVector4((Color)_themeColor_000000));
                }
            }
        }

        public Color Color_FF0000
        {
            get => _themeColor_FF0000;
            set
            {
                _themeColor_FF0000 = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Color_FF0000", ColorAsVector4((Color)_themeColor_FF0000));
                }
            }
        }

        public Color Color_FFFFFF
        {
            get => _themeColor_FFFFFF;
            set
            {
                _themeColor_FFFFFF = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Color_FFFFFF", ColorAsVector4((Color)_themeColor_FFFFFF));
                }
            }
        }

        static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties == null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Color_000000", ColorAsVector4((Color)Color_000000));
                _themeProperties.InsertVector4("Color_FF0000", ColorAsVector4((Color)Color_FF0000));
                _themeProperties.InsertVector4("Color_FFFFFF", ColorAsVector4((Color)Color_FFFFFF));
            }
            return _themeProperties;
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            if (ChecklistSelect_AnimatedVisual_UAPv15.IsRuntimeCompatible())
            {
                var res = 
                    new ChecklistSelect_AnimatedVisual_UAPv15(
                        compositor,
                        _themeProperties
                        );
                    return res;
            }

            if (ChecklistSelect_AnimatedVisual_UAPv8.IsRuntimeCompatible())
            {
                var res = 
                    new ChecklistSelect_AnimatedVisual_UAPv8(
                        compositor,
                        _themeProperties
                        );
                    return res;
            }

            return null;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 33d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 100d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(2500000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 33d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
            if (propertyName == "Color_000000")
            {
                _themeColor_000000 = value;
            }
            else if (propertyName == "Color_FF0000")
            {
                _themeColor_FF0000 = value;
            }
            else if (propertyName == "Color_FFFFFF")
            {
                _themeColor_FFFFFF = value;
            }
            else
            {
                return;
            }

            if (_themeProperties != null)
            {
                _themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
            }
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class ChecklistSelect_AnimatedVisual_UAPv15
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
        {
            const long c_durationTicks = 2500000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            AnimationController _animationController_0;
            ContainerVisual _root;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            AnimationController AnimationController_0()
            {
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(result, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - - - - - Shape tree root for layer: Vector 1
            // - - - - ShapeGroup: Vector 1
            CanvasGeometry Geometry()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(4.5F, -3F));
                    builder.AddLine(new Vector2(-1.31799996F, 3F));
                    builder.AddLine(new Vector2(-4.5F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - - - - Transforms: Shape Layer 1: 0-stroke-mask
            // - - ShapeGroup: Shape Layer 1
            // Color bound to theme property value: Color_000000
            CompositionColorBrush ThemeColor_Color_000000()
            {
                var result = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_000000.W,_theme.Color_000000.X,_theme.Color_000000.Y,_theme.Color_000000.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - - - - - - Shape tree root for layer: accent
            // - - - - ShapeGroup: 
            // - - ShapeGroup: Ellipse 5
            // Color bound to theme property value: Color_FF0000
            CompositionColorBrush ThemeColor_Color_FF0000_0()
            {
                var result = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_FF0000.W,_theme.Color_FF0000.X,_theme.Color_FF0000.Y,_theme.Color_FF0000.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - - - - - Shape tree root for layer: Shape Layer 1: 0
            // - - - - Transforms: Shape Layer 1: 0
            // - - ShapeGroup: Shape Layer 1
            // Color bound to theme property value: Color_FF0000
            CompositionColorBrush ThemeColor_Color_FF0000_1()
            {
                var result = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_FF0000.W,_theme.Color_FF0000.X,_theme.Color_FF0000.Y,_theme.Color_FF0000.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - - - - Shape tree root for layer: Vector 1
            // - - ShapeGroup: Vector 1
            // Color bound to theme property value: Color_FFFFFF
            CompositionColorBrush ThemeColor_Color_FFFFFF()
            {
                var result = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_FFFFFF.W,_theme.Color_FFFFFF.X,_theme.Color_FFFFFF.Y,_theme.Color_FFFFFF.Z)", "_theme", _themeProperties);
                return result;
            }

            // Shape tree root for layer: accent
            CompositionContainerShape ContainerShape_00()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_01());
                return result;
            }

            // - Shape tree root for layer: accent
            CompositionContainerShape ContainerShape_01()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup:
                result.Shapes.Add(ContainerShape_02());
                return result;
            }

            // - - Shape tree root for layer: accent
            // ShapeGroup:
            CompositionContainerShape ContainerShape_02()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(12F, 12F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_03());
                return result;
            }

            // - - - Shape tree root for layer: accent
            // ShapeGroup:
            CompositionContainerShape ContainerShape_03()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Ellipse 5
                result.Shapes.Add(ContainerShape_04());
                return result;
            }

            // - - - - Shape tree root for layer: accent
            // - ShapeGroup: 
            // ShapeGroup: Ellipse 5
            CompositionContainerShape ContainerShape_04()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Shapes.Add(ContainerShape_05());
                result.StartAnimation("Scale", ScaleVector2Animation(), AnimationController_0());
                return result;
            }

            // - - - - - Shape tree root for layer: accent
            // - - ShapeGroup: 
            // ShapeGroup: Ellipse 5
            CompositionContainerShape ContainerShape_05()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(SpriteShape_0());
                return result;
            }

            // Shape tree root for layer: Shape Layer 1: 0
            CompositionContainerShape ContainerShape_06()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                // Transforms: Shape Layer 1: 0
                result.Shapes.Add(ContainerShape_07());
                return result;
            }

            // - Shape tree root for layer: Shape Layer 1: 0
            // Transforms for Shape Layer 1: 0
            CompositionContainerShape ContainerShape_07()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_08());
                return result;
            }

            // - - Shape tree root for layer: Shape Layer 1: 0
            // Transforms: Shape Layer 1: 0
            CompositionContainerShape ContainerShape_08()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Shape Layer 1
                result.Shapes.Add(ContainerShape_09());
                return result;
            }

            // - - - Shape tree root for layer: Shape Layer 1: 0
            // - Transforms: Shape Layer 1: 0
            // ShapeGroup: Shape Layer 1
            CompositionContainerShape ContainerShape_09()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(12F, 12F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_10());
                return result;
            }

            // - - - - Shape tree root for layer: Shape Layer 1: 0
            // - - Transforms: Shape Layer 1: 0
            // ShapeGroup: Shape Layer 1
            CompositionContainerShape ContainerShape_10()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(SpriteShape_1());
                return result;
            }

            // Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            CompositionContainerShape ContainerShape_11()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                // Transforms: Shape Layer 1: 0-stroke-mask
                result.Shapes.Add(ContainerShape_12());
                return result;
            }

            // - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // Transforms for Shape Layer 1: 0-stroke-mask
            CompositionContainerShape ContainerShape_12()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_13());
                return result;
            }

            // - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // Transforms: Shape Layer 1: 0-stroke-mask
            CompositionContainerShape ContainerShape_13()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Shape Layer 1
                result.Shapes.Add(ContainerShape_14());
                return result;
            }

            // - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - Transforms: Shape Layer 1: 0-stroke-mask
            // ShapeGroup: Shape Layer 1
            CompositionContainerShape ContainerShape_14()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(12F, 12F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_15());
                return result;
            }

            // - - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - - Transforms: Shape Layer 1: 0-stroke-mask
            // ShapeGroup: Shape Layer 1
            CompositionContainerShape ContainerShape_15()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(SpriteShape_2());
                return result;
            }

            // Shape tree root for layer: Vector 1
            CompositionContainerShape ContainerShape_16()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_17());
                return result;
            }

            // - Shape tree root for layer: Vector 1
            CompositionContainerShape ContainerShape_17()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Vector 1
                result.Shapes.Add(ContainerShape_18());
                return result;
            }

            // - - Shape tree root for layer: Vector 1
            // ShapeGroup: Vector 1
            CompositionContainerShape ContainerShape_18()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(12F, 12F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_19());
                return result;
            }

            // - - - Shape tree root for layer: Vector 1
            // ShapeGroup: Vector 1
            CompositionContainerShape ContainerShape_19()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(SpriteShape_3());
                return result;
            }

            CompositionEffectBrush EffectBrush()
            {
                var effectFactory = EffectFactory();
                var result = effectFactory.CreateBrush();
                result.SetSourceParameter("destination", SurfaceBrush_0());
                result.SetSourceParameter("source", SurfaceBrush_1());
                return result;
            }

            CompositionEffectFactory EffectFactory()
            {
                var compositeEffect = new CompositeEffect();
                compositeEffect.Mode = CanvasComposite.DestinationIn;
                compositeEffect.Sources.Add(new CompositionEffectSourceParameter("destination"));
                compositeEffect.Sources.Add(new CompositionEffectSourceParameter("source"));
                var result = _c.CreateEffectFactory(compositeEffect);
                return result;
            }

            // - - - - - - - Shape tree root for layer: accent
            // - - - - ShapeGroup: 
            // - - ShapeGroup: Ellipse 5
            // .EllipseGeometry
            CompositionEllipseGeometry Ellipse_9()
            {
                var result = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(9F, 9F);
                return result;
            }

            // - - - - - - Shape tree root for layer: Shape Layer 1: 0
            // - - - - Transforms: Shape Layer 1: 0
            // - - ShapeGroup: Shape Layer 1
            // .EllipseGeometry
            CompositionEllipseGeometry Ellipse_10_0()
            {
                var result = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(10F, 10F);
                return result;
            }

            // - - - - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - - - - Transforms: Shape Layer 1: 0-stroke-mask
            // - - ShapeGroup: Shape Layer 1
            // .EllipseGeometry
            CompositionEllipseGeometry Ellipse_10_1()
            {
                var result = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(10F, 10F);
                return result;
            }

            // - - - - - Shape tree root for layer: Vector 1
            // - - ShapeGroup: Vector 1
            CompositionPathGeometry PathGeometry()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry()));
                result.TrimEnd = 1F;
                result.TrimOffset = 0F;
                result.StartAnimation("TrimStart", TrimStartScalarAnimation_1_to_0(), _animationController_0);
                return result;
            }

            // - - - - - - Shape tree root for layer: accent
            // - - - ShapeGroup: 
            // - ShapeGroup: Ellipse 5
            CompositionSpriteShape SpriteShape_0()
            {
                var result = _c.CreateSpriteShape(Ellipse_9());
                result.FillBrush = ThemeColor_Color_FF0000_0();
                return result;
            }

            // - - - - - Shape tree root for layer: Shape Layer 1: 0
            // - - - Transforms: Shape Layer 1: 0
            // - ShapeGroup: Shape Layer 1
            CompositionSpriteShape SpriteShape_1()
            {
                var result = _c.CreateSpriteShape(Ellipse_10_0());
                result.StrokeBrush = ThemeColor_Color_FF0000_1();
                result.StrokeDashOffset = 0F;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 3F;
                return result;
            }

            // - - - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - - - Transforms: Shape Layer 1: 0-stroke-mask
            // - ShapeGroup: Shape Layer 1
            CompositionSpriteShape SpriteShape_2()
            {
                var result = _c.CreateSpriteShape(Ellipse_10_1());
                result.FillBrush = ThemeColor_Color_000000();
                return result;
            }

            // - - - - Shape tree root for layer: Vector 1
            // - ShapeGroup: Vector 1
            CompositionSpriteShape SpriteShape_3()
            {
                var result = _c.CreateSpriteShape(PathGeometry());
                result.StrokeBrush = ThemeColor_Color_FFFFFF();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeDashOffset = 0F;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 1.5F;
                return result;
            }

            CompositionSurfaceBrush SurfaceBrush_0()
            {
                return _c.CreateSurfaceBrush(VisualSurface_0());
            }

            CompositionSurfaceBrush SurfaceBrush_1()
            {
                return _c.CreateSurfaceBrush(VisualSurface_1());
            }

            CompositionVisualSurface VisualSurface_0()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_1();
                result.SourceSize = new Vector2(24F, 24F);
                result.SourceOffset = new Vector2(0F, 0F);
                return result;
            }

            CompositionVisualSurface VisualSurface_1()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_3();
                result.SourceSize = new Vector2(24F, 24F);
                result.SourceOffset = new Vector2(0F, 0F);
                return result;
            }

            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                // Shape tree root for layer: accent
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            ContainerVisual ContainerVisual_1()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                result.Children.InsertAtTop(ContainerVisual_2());
                return result;
            }

            ContainerVisual ContainerVisual_2()
            {
                var result = _c.CreateContainerVisual();
                // Shape tree root for layer: Shape Layer 1: 0
                result.Children.InsertAtTop(ShapeVisual_1());
                return result;
            }

            ContainerVisual ContainerVisual_3()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                result.Children.InsertAtTop(ContainerVisual_4());
                return result;
            }

            ContainerVisual ContainerVisual_4()
            {
                var result = _c.CreateContainerVisual();
                // Shape tree root for layer: Shape Layer 1: 0-stroke-mask
                result.Children.InsertAtTop(ShapeVisual_2());
                return result;
            }

            ContainerVisual ContainerVisual_5()
            {
                var result = _c.CreateContainerVisual();
                // Shape tree root for layer: Vector 1
                result.Children.InsertAtTop(ShapeVisual_3());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                var children = result.Children;
                children.InsertAtTop(ContainerVisual_0());
                children.InsertAtTop(SpriteVisual_0());
                children.InsertAtTop(ContainerVisual_5());
                return result;
            }

            // - - - - - - Shape tree root for layer: Vector 1
            // - - - ShapeGroup: Vector 1
            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_1_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 1F, _stepThenHoldEasingFunction);
                // Frame 15.
                result.InsertKeyFrame(0.454545468F, 1F, _holdThenStepEasingFunction);
                // Frame 32.
                result.InsertKeyFrame(0.969696999F, 0F, _c.CreateCubicBezierEasingFunction(new Vector2(0.600000024F, 0F), new Vector2(0.400000006F, 1F)));
                return result;
            }

            // Shape tree root for layer: accent
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(24F, 24F);
                result.Shapes.Add(ContainerShape_00());
                return result;
            }

            // Shape tree root for layer: Shape Layer 1: 0
            ShapeVisual ShapeVisual_1()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(24F, 24F);
                result.Shapes.Add(ContainerShape_06());
                return result;
            }

            // Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            ShapeVisual ShapeVisual_2()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(24F, 24F);
                result.Shapes.Add(ContainerShape_11());
                return result;
            }

            // Shape tree root for layer: Vector 1
            ShapeVisual ShapeVisual_3()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(24F, 24F);
                result.Shapes.Add(ContainerShape_16());
                return result;
            }

            SpriteVisual SpriteVisual_0()
            {
                var result = _c.CreateSpriteVisual();
                result.Offset = new Vector3(0F, 0F, 0F);
                result.Size = new Vector2(24F, 24F);
                result.Brush = EffectBrush();
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.FinalStep = 1;
                result.IsFinalStepSingleFrame = true;
                result.StepCount = 1;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.FinalStep = 1;
                result.IsInitialStepSingleFrame = true;
                result.StepCount = 1;
                return result;
            }

            // - - - - - Shape tree root for layer: accent
            // - - ShapeGroup: 
            // ShapeGroup: Ellipse 5
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), StepThenHoldEasingFunction());
                // Frame 2.
                result.InsertKeyFrame(0.0606060624F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 32.
                result.InsertKeyFrame(0.969696999F, new Vector2(1F, 1F), _c.CreateCubicBezierEasingFunction(new Vector2(0.600000024F, 0F), new Vector2(0.400000006F, 1F)));
                return result;
            }

            internal ChecklistSelect_AnimatedVisual_UAPv15(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(24F, 24F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 15);
            }
        }

        sealed partial class ChecklistSelect_AnimatedVisual_UAPv8
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
        {
            const long c_durationTicks = 2500000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            ContainerVisual _root;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            // - - - - - - - Shape tree root for layer: Vector 1
            // - - - - ShapeGroup: Vector 1
            CanvasGeometry Geometry()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(4.5F, -3F));
                    builder.AddLine(new Vector2(-1.31799996F, 3F));
                    builder.AddLine(new Vector2(-4.5F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - - - - Transforms: Shape Layer 1: 0-stroke-mask
            // - - ShapeGroup: Shape Layer 1
            // Color bound to theme property value: Color_000000
            CompositionColorBrush ThemeColor_Color_000000()
            {
                var result = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_000000.W,_theme.Color_000000.X,_theme.Color_000000.Y,_theme.Color_000000.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - - - - - - Shape tree root for layer: accent
            // - - - - ShapeGroup: 
            // - - ShapeGroup: Ellipse 5
            // Color bound to theme property value: Color_FF0000
            CompositionColorBrush ThemeColor_Color_FF0000_0()
            {
                var result = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_FF0000.W,_theme.Color_FF0000.X,_theme.Color_FF0000.Y,_theme.Color_FF0000.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - - - - - Shape tree root for layer: Shape Layer 1: 0
            // - - - - Transforms: Shape Layer 1: 0
            // - - ShapeGroup: Shape Layer 1
            // Color bound to theme property value: Color_FF0000
            CompositionColorBrush ThemeColor_Color_FF0000_1()
            {
                var result = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_FF0000.W,_theme.Color_FF0000.X,_theme.Color_FF0000.Y,_theme.Color_FF0000.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - - - - Shape tree root for layer: Vector 1
            // - - ShapeGroup: Vector 1
            // Color bound to theme property value: Color_FFFFFF
            CompositionColorBrush ThemeColor_Color_FFFFFF()
            {
                var result = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_FFFFFF.W,_theme.Color_FFFFFF.X,_theme.Color_FFFFFF.Y,_theme.Color_FFFFFF.Z)", "_theme", _themeProperties);
                return result;
            }

            // Shape tree root for layer: accent
            CompositionContainerShape ContainerShape_00()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_01());
                return result;
            }

            // - Shape tree root for layer: accent
            CompositionContainerShape ContainerShape_01()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup:
                result.Shapes.Add(ContainerShape_02());
                return result;
            }

            // - - Shape tree root for layer: accent
            // ShapeGroup:
            CompositionContainerShape ContainerShape_02()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(12F, 12F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_03());
                return result;
            }

            // - - - Shape tree root for layer: accent
            // ShapeGroup:
            CompositionContainerShape ContainerShape_03()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Ellipse 5
                result.Shapes.Add(ContainerShape_04());
                return result;
            }

            // - - - - Shape tree root for layer: accent
            // - ShapeGroup: 
            // ShapeGroup: Ellipse 5
            CompositionContainerShape ContainerShape_04()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Shapes.Add(ContainerShape_05());
                result.StartAnimation("Scale", ScaleVector2Animation());
                var controller = result.TryGetAnimationController("Scale");
                controller.Pause();
                BindProperty(controller, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - - - Shape tree root for layer: accent
            // - - ShapeGroup: 
            // ShapeGroup: Ellipse 5
            CompositionContainerShape ContainerShape_05()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(SpriteShape_0());
                return result;
            }

            // Shape tree root for layer: Shape Layer 1: 0
            CompositionContainerShape ContainerShape_06()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                // Transforms: Shape Layer 1: 0
                result.Shapes.Add(ContainerShape_07());
                return result;
            }

            // - Shape tree root for layer: Shape Layer 1: 0
            // Transforms for Shape Layer 1: 0
            CompositionContainerShape ContainerShape_07()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_08());
                return result;
            }

            // - - Shape tree root for layer: Shape Layer 1: 0
            // Transforms: Shape Layer 1: 0
            CompositionContainerShape ContainerShape_08()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Shape Layer 1
                result.Shapes.Add(ContainerShape_09());
                return result;
            }

            // - - - Shape tree root for layer: Shape Layer 1: 0
            // - Transforms: Shape Layer 1: 0
            // ShapeGroup: Shape Layer 1
            CompositionContainerShape ContainerShape_09()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(12F, 12F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_10());
                return result;
            }

            // - - - - Shape tree root for layer: Shape Layer 1: 0
            // - - Transforms: Shape Layer 1: 0
            // ShapeGroup: Shape Layer 1
            CompositionContainerShape ContainerShape_10()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(SpriteShape_1());
                return result;
            }

            // Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            CompositionContainerShape ContainerShape_11()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                // Transforms: Shape Layer 1: 0-stroke-mask
                result.Shapes.Add(ContainerShape_12());
                return result;
            }

            // - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // Transforms for Shape Layer 1: 0-stroke-mask
            CompositionContainerShape ContainerShape_12()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_13());
                return result;
            }

            // - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // Transforms: Shape Layer 1: 0-stroke-mask
            CompositionContainerShape ContainerShape_13()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Shape Layer 1
                result.Shapes.Add(ContainerShape_14());
                return result;
            }

            // - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - Transforms: Shape Layer 1: 0-stroke-mask
            // ShapeGroup: Shape Layer 1
            CompositionContainerShape ContainerShape_14()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(12F, 12F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_15());
                return result;
            }

            // - - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - - Transforms: Shape Layer 1: 0-stroke-mask
            // ShapeGroup: Shape Layer 1
            CompositionContainerShape ContainerShape_15()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(SpriteShape_2());
                return result;
            }

            // Shape tree root for layer: Vector 1
            CompositionContainerShape ContainerShape_16()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(0F, 0F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_17());
                return result;
            }

            // - Shape tree root for layer: Vector 1
            CompositionContainerShape ContainerShape_17()
            {
                var result = _c.CreateContainerShape();
                // ShapeGroup: Vector 1
                result.Shapes.Add(ContainerShape_18());
                return result;
            }

            // - - Shape tree root for layer: Vector 1
            // ShapeGroup: Vector 1
            CompositionContainerShape ContainerShape_18()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(0F, 0F);
                result.Offset = new Vector2(12F, 12F);
                result.RotationAngleInDegrees = 0F;
                result.Scale = new Vector2(1F, 1F);
                result.Shapes.Add(ContainerShape_19());
                return result;
            }

            // - - - Shape tree root for layer: Vector 1
            // ShapeGroup: Vector 1
            CompositionContainerShape ContainerShape_19()
            {
                var result = _c.CreateContainerShape();
                result.Shapes.Add(SpriteShape_3());
                return result;
            }

            CompositionEffectBrush EffectBrush()
            {
                var effectFactory = EffectFactory();
                var result = effectFactory.CreateBrush();
                result.SetSourceParameter("destination", SurfaceBrush_0());
                result.SetSourceParameter("source", SurfaceBrush_1());
                return result;
            }

            CompositionEffectFactory EffectFactory()
            {
                var compositeEffect = new CompositeEffect();
                compositeEffect.Mode = CanvasComposite.DestinationIn;
                compositeEffect.Sources.Add(new CompositionEffectSourceParameter("destination"));
                compositeEffect.Sources.Add(new CompositionEffectSourceParameter("source"));
                var result = _c.CreateEffectFactory(compositeEffect);
                return result;
            }

            // - - - - - - - Shape tree root for layer: accent
            // - - - - ShapeGroup: 
            // - - ShapeGroup: Ellipse 5
            // .EllipseGeometry
            CompositionEllipseGeometry Ellipse_9()
            {
                var result = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(9F, 9F);
                return result;
            }

            // - - - - - - Shape tree root for layer: Shape Layer 1: 0
            // - - - - Transforms: Shape Layer 1: 0
            // - - ShapeGroup: Shape Layer 1
            // .EllipseGeometry
            CompositionEllipseGeometry Ellipse_10_0()
            {
                var result = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(10F, 10F);
                return result;
            }

            // - - - - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - - - - Transforms: Shape Layer 1: 0-stroke-mask
            // - - ShapeGroup: Shape Layer 1
            // .EllipseGeometry
            CompositionEllipseGeometry Ellipse_10_1()
            {
                var result = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(10F, 10F);
                return result;
            }

            // - - - - - Shape tree root for layer: Vector 1
            // - - ShapeGroup: Vector 1
            CompositionPathGeometry PathGeometry()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry()));
                result.TrimEnd = 1F;
                result.TrimOffset = 0F;
                result.StartAnimation("TrimStart", TrimStartScalarAnimation_1_to_0());
                var controller = result.TryGetAnimationController("TrimStart");
                controller.Pause();
                BindProperty(controller, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - - - - Shape tree root for layer: accent
            // - - - ShapeGroup: 
            // - ShapeGroup: Ellipse 5
            CompositionSpriteShape SpriteShape_0()
            {
                var result = _c.CreateSpriteShape(Ellipse_9());
                result.FillBrush = ThemeColor_Color_FF0000_0();
                return result;
            }

            // - - - - - Shape tree root for layer: Shape Layer 1: 0
            // - - - Transforms: Shape Layer 1: 0
            // - ShapeGroup: Shape Layer 1
            CompositionSpriteShape SpriteShape_1()
            {
                var result = _c.CreateSpriteShape(Ellipse_10_0());
                result.StrokeBrush = ThemeColor_Color_FF0000_1();
                result.StrokeDashOffset = 0F;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 3F;
                return result;
            }

            // - - - - - Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            // - - - Transforms: Shape Layer 1: 0-stroke-mask
            // - ShapeGroup: Shape Layer 1
            CompositionSpriteShape SpriteShape_2()
            {
                var result = _c.CreateSpriteShape(Ellipse_10_1());
                result.FillBrush = ThemeColor_Color_000000();
                return result;
            }

            // - - - - Shape tree root for layer: Vector 1
            // - ShapeGroup: Vector 1
            CompositionSpriteShape SpriteShape_3()
            {
                var result = _c.CreateSpriteShape(PathGeometry());
                result.StrokeBrush = ThemeColor_Color_FFFFFF();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeDashOffset = 0F;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 1.5F;
                return result;
            }

            CompositionSurfaceBrush SurfaceBrush_0()
            {
                return _c.CreateSurfaceBrush(VisualSurface_0());
            }

            CompositionSurfaceBrush SurfaceBrush_1()
            {
                return _c.CreateSurfaceBrush(VisualSurface_1());
            }

            CompositionVisualSurface VisualSurface_0()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_1();
                result.SourceSize = new Vector2(24F, 24F);
                result.SourceOffset = new Vector2(0F, 0F);
                return result;
            }

            CompositionVisualSurface VisualSurface_1()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_3();
                result.SourceSize = new Vector2(24F, 24F);
                result.SourceOffset = new Vector2(0F, 0F);
                return result;
            }

            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                // Shape tree root for layer: accent
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            ContainerVisual ContainerVisual_1()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                result.Children.InsertAtTop(ContainerVisual_2());
                return result;
            }

            ContainerVisual ContainerVisual_2()
            {
                var result = _c.CreateContainerVisual();
                // Shape tree root for layer: Shape Layer 1: 0
                result.Children.InsertAtTop(ShapeVisual_1());
                return result;
            }

            ContainerVisual ContainerVisual_3()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                result.Children.InsertAtTop(ContainerVisual_4());
                return result;
            }

            ContainerVisual ContainerVisual_4()
            {
                var result = _c.CreateContainerVisual();
                // Shape tree root for layer: Shape Layer 1: 0-stroke-mask
                result.Children.InsertAtTop(ShapeVisual_2());
                return result;
            }

            ContainerVisual ContainerVisual_5()
            {
                var result = _c.CreateContainerVisual();
                // Shape tree root for layer: Vector 1
                result.Children.InsertAtTop(ShapeVisual_3());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                var children = result.Children;
                children.InsertAtTop(ContainerVisual_0());
                children.InsertAtTop(SpriteVisual_0());
                children.InsertAtTop(ContainerVisual_5());
                return result;
            }

            // - - - - - - Shape tree root for layer: Vector 1
            // - - - ShapeGroup: Vector 1
            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_1_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 1F, _stepThenHoldEasingFunction);
                // Frame 15.
                result.InsertKeyFrame(0.454545468F, 1F, _holdThenStepEasingFunction);
                // Frame 32.
                result.InsertKeyFrame(0.969696999F, 0F, _c.CreateCubicBezierEasingFunction(new Vector2(0.600000024F, 0F), new Vector2(0.400000006F, 1F)));
                return result;
            }

            // Shape tree root for layer: accent
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(24F, 24F);
                result.Shapes.Add(ContainerShape_00());
                return result;
            }

            // Shape tree root for layer: Shape Layer 1: 0
            ShapeVisual ShapeVisual_1()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(24F, 24F);
                result.Shapes.Add(ContainerShape_06());
                return result;
            }

            // Shape tree root for layer: Shape Layer 1: 0-stroke-mask
            ShapeVisual ShapeVisual_2()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(24F, 24F);
                result.Shapes.Add(ContainerShape_11());
                return result;
            }

            // Shape tree root for layer: Vector 1
            ShapeVisual ShapeVisual_3()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(24F, 24F);
                result.Shapes.Add(ContainerShape_16());
                return result;
            }

            SpriteVisual SpriteVisual_0()
            {
                var result = _c.CreateSpriteVisual();
                result.Offset = new Vector3(0F, 0F, 0F);
                result.Size = new Vector2(24F, 24F);
                result.Brush = EffectBrush();
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.FinalStep = 1;
                result.IsFinalStepSingleFrame = true;
                result.StepCount = 1;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.FinalStep = 1;
                result.IsInitialStepSingleFrame = true;
                result.StepCount = 1;
                return result;
            }

            // - - - - - Shape tree root for layer: accent
            // - - ShapeGroup: 
            // ShapeGroup: Ellipse 5
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), StepThenHoldEasingFunction());
                // Frame 2.
                result.InsertKeyFrame(0.0606060624F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 32.
                result.InsertKeyFrame(0.969696999F, new Vector2(1F, 1F), _c.CreateCubicBezierEasingFunction(new Vector2(0.600000024F, 0F), new Vector2(0.400000006F, 1F)));
                return result;
            }

            internal ChecklistSelect_AnimatedVisual_UAPv8(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(24F, 24F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 8);
            }
        }
    }
}
