namespace Telegram.Native.Opus
{
    [bindable]
    [default_interface]
    runtimeclass OpusOutput : Windows.Foundation.IClosable
    {
        OpusOutput(String fileName);
        Boolean IsValid{ get; };
        void Transcode(String fileName);
    }
}
