// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getChats.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesChats"/>
	/// </summary>
	public partial class TLMessagesGetChats : TLObject
	{
		public TLVector<Int32> Id { get; set; }

		public TLMessagesGetChats() { }
		public TLMessagesGetChats(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetChats; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLVector<Int32>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3C6AA187);
			to.WriteObject(Id);
		}
	}
}