// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.setBotCallbackAnswer
	/// </summary>
	public partial class TLMessagesSetBotCallbackAnswer : TLObject
	{
		[Flags]
		public enum Flag : Int32
		{
			Alert = (1 << 1),
			Message = (1 << 0),
		}

		public bool IsAlert { get { return Flags.HasFlag(Flag.Alert); } set { Flags = value ? (Flags | Flag.Alert) : (Flags & ~Flag.Alert); } }
		public bool HasMessage { get { return Flags.HasFlag(Flag.Message); } set { Flags = value ? (Flags | Flag.Message) : (Flags & ~Flag.Message); } }

		public Flag Flags { get; set; }
		public Int64 QueryId { get; set; }
		public String Message { get; set; }

		public TLMessagesSetBotCallbackAnswer() { }
		public TLMessagesSetBotCallbackAnswer(TLBinaryReader from, TLType type = TLType.MessagesSetBotCallbackAnswer)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.MessagesSetBotCallbackAnswer; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.MessagesSetBotCallbackAnswer)
		{
			Flags = (Flag)from.ReadInt32();
			QueryId = from.ReadInt64();
			if (HasMessage) { Message = from.ReadString(); }
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x481C591A);
			to.Write((Int32)Flags);
			to.Write(QueryId);
			if (HasMessage) to.Write(Message);
		}
	}
}