// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.saveGif
	/// </summary>
	public partial class TLMessagesSaveGif : TLObject
	{
		public TLInputDocumentBase Id { get; set; }
		public Boolean Unsave { get; set; }

		public TLMessagesSaveGif() { }
		public TLMessagesSaveGif(TLBinaryReader from, TLType type = TLType.MessagesSaveGif)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.MessagesSaveGif; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.MessagesSaveGif)
		{
			Id = TLFactory.Read<TLInputDocumentBase>(from);
			Unsave = from.ReadBoolean();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x327A30CB);
			to.WriteObject(Id);
			to.Write(Unsave);
		}
	}
}