// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.toggleChatAdmins
	/// </summary>
	public partial class TLMessagesToggleChatAdmins : TLObject
	{
		public Int32 ChatId { get; set; }
		public Boolean Enabled { get; set; }

		public TLMessagesToggleChatAdmins() { }
		public TLMessagesToggleChatAdmins(TLBinaryReader from, TLType type = TLType.MessagesToggleChatAdmins)
		{
			Read(from, type);
		}

		public override TLType TypeId { get { return TLType.MessagesToggleChatAdmins; } }

		public override void Read(TLBinaryReader from, TLType type = TLType.MessagesToggleChatAdmins)
		{
			ChatId = from.ReadInt32();
			Enabled = from.ReadBoolean();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEC8BD9E1);
			to.Write(ChatId);
			to.Write(Enabled);
		}
	}
}