// <auto-generated/>
using System;
using Telegram.Api.Native.TL;

namespace Telegram.Api.TL.Methods
{
	/// <summary>
	/// RCP method invokeAfterMsgs.
	/// Returns <see cref="Telegram.Api.TL.TLObject"/>
	/// </summary>
	public partial class TLInvokeAfterMsgs : TLObject
	{
		public TLVector<Int64> MsgIds { get; set; }
		public TLObject Query { get; set; }

		public TLInvokeAfterMsgs() { }
		public TLInvokeAfterMsgs(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InvokeAfterMsgs; } }

		public override void Read(TLBinaryReader from)
		{
			MsgIds = TLFactory.Read<TLVector<Int64>>(from);
			Query = TLFactory.Read<TLObject>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.WriteObject(MsgIds);
			to.WriteObject(Query);
		}
	}
}