<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <UseUwpTools>true</UseUwpTools>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <DefaultLanguage>en-US</DefaultLanguage>
    <PublishAot>true</PublishAot>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <EnableMsixTooling>true</EnableMsixTooling>
    <!--<PackageCertificateKeyFile>
    </PackageCertificateKeyFile>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>True</AppxSymbolPackageEnabled>
    <AppxBundle>Always</AppxBundle>
    <AppxBundlePlatforms>x64</AppxBundlePlatforms>
    <PackageCertificateKeyFile>Telegram_TemporaryKey.pfx</PackageCertificateKeyFile>
    <BuildAppxSideloadPackageForUap>False</BuildAppxSideloadPackageForUap>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppInstallerUpdateFrequency>0</AppInstallerUpdateFrequency>
    <AppInstallerCheckForUpdateFrequency>OnApplicationRun</AppInstallerCheckForUpdateFrequency>
    <GenerateTestArtifacts>False</GenerateTestArtifacts>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <ProjectPriIndexName>Telegram</ProjectPriIndexName>
    <PackageCertificateThumbprint>
    </PackageCertificateThumbprint>-->
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <PackageCertificateKeyFile>..\Telegram.Msix\Telegram.Msix_TemporaryKey.pfx</PackageCertificateKeyFile>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <AppxBundle>Never</AppxBundle>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <EnableDefaultItems>true</EnableDefaultItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);ENABLE_CALLS</DefineConstants>
    <IncludePublishItemsOutputGroup>true</IncludePublishItemsOutputGroup>
  </PropertyGroup>

  <PropertyGroup>
    <CSWinRTIncludes>
      Telegram.Native;Telegram.Native.Calls;RLottie;
    </CSWinRTIncludes>
    <CSWinRTWindowsMetadata>local</CSWinRTWindowsMetadata>
    <CsWinRTGenerateProjection>true</CsWinRTGenerateProjection>
  </PropertyGroup>

  <ItemGroup>
    <RdXmlFile Include="Rd.xml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AppPackages\**" />
    <Compile Remove="Assets\Mockup\**" />
    <Compile Remove="BundleArtifacts\**" />
    <Compile Remove="Generated Files\**" />
    <Content Remove="Assets\Mockup\**" />
    <EmbeddedResource Remove="AppPackages\**" />
    <EmbeddedResource Remove="Assets\Mockup\**" />
    <EmbeddedResource Remove="BundleArtifacts\**" />
    <EmbeddedResource Remove="Generated Files\**" />
    <None Remove="AppPackages\**" />
    <None Remove="Assets\Mockup\**" />
    <None Remove="BundleArtifacts\**" />
    <None Remove="Generated Files\**" />
    <Page Remove="AppPackages\**" />
    <Page Remove="Assets\Mockup\**" />
    <Page Remove="BundleArtifacts\**" />
    <Page Remove="Generated Files\**" />
    <PRIResource Remove="AppPackages\**" />
    <PRIResource Remove="BundleArtifacts\**" />
    <PRIResource Remove="Generated Files\**" />
    <Content Remove="Assets\i420.bat" />
    <Content Remove="Assets\i420.fxlib" />
    <PRIResource Remove="Assets\Mockup\**" />
    <Compile Remove="Common\HttpServer.cs" />
    <Compile Remove="Common\LocalDatabase.cs" />
    <Compile Remove="Common\ParticlesLayer.cs" />
    <Compile Remove="Services\ProxyService.cs" />
    <Content Remove="Assets\Fonts\Telegram.json" />
    <Content Remove="Assets\Icons\ActionFile.json" />
    <Content Remove="Assets\Icons\ActionGame.json" />
    <Content Remove="Assets\Icons\ActionSticker.json" />
    <Content Remove="Assets\Icons\ActionTyping.json" />
    <Content Remove="Assets\Icons\ActionVideo.json" />
    <Content Remove="Assets\Icons\ActionVoice.json" />
    <Content Remove="Assets\Icons\Business.json" />
    <Content Remove="Assets\Icons\Dots.json" />
    <Content Remove="Assets\Icons\More.json" />
    <Content Remove="Assets\Icons\PremiumGifting.json" />
    <Content Remove="Assets\Icons\TeachingTipLinkCopied.json" />
    <Content Remove="Assets\Icons\VoiceRecognition.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.HashCode">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.2.14</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.UI.Xaml">
      <Version>2.8.7</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Web.WebView2">
      <Version>1.0.3240.44</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.3</Version>
    </PackageReference>
    <PackageReference Include="Rg.DiffUtils">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="SharpDX.Direct3D11">
      <Version>4.2.0</Version>
    </PackageReference>
    <PackageReference Include="System.Memory">
      <Version>4.6.3</Version>
    </PackageReference>
    <PackageReference Include="System.ValueTuple">
      <Version>4.6.1</Version>
    </PackageReference>
    <PackageReference Include="Telegram.Td.UWP">
      <Version>1.8.50</Version>
    </PackageReference>
    <PackageReference Include="VideoLAN.LibVLC.UWP">
      <Version>3.0.21</Version>
    </PackageReference>
    <PackageReference Include="Win2D.uwp">
      <Version>1.28.3</Version>
    </PackageReference>
    <!-- Used by AppCenter -->
    <PackageReference Include="SQLitePCLRaw.bundle_winsqlite3">
      <Version>2.1.11</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.Metadata">
      <Version>9.0.5</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Telegram.Native.Calls\Telegram.Native.Calls.vcxproj">
      <Project>{fdd3c45d-4cff-4a90-8fef-16ca70ab00be}</Project>
      <Name>Telegram.Native.Calls</Name>
    </ProjectReference>
    <ProjectReference Include="..\Telegram.Native\Telegram.Native.vcxproj">
      <Project>{1b521e77-46bd-4d60-89f6-d68e9bb9abff}</Project>
      <Name>Telegram.Native</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.AppCenter, Version=0.0.0.0, Culture=neutral, PublicKeyToken=8a600e2fee7ba272, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Libraries\AppCenter\Microsoft.AppCenter.dll</HintPath>
    </Reference>
    <Reference Include="RLottie">
      <HintPath>$(ProjectDir)\..\Libraries\rlottie\$(Platform)\RLottie.winmd</HintPath>
      <Implementation>RLottie.dll</Implementation>
    </Reference>
    <ReferenceCopyLocalPaths Include="$(ProjectDir)\..\Libraries\rlottie\$(Platform)\RLottie.dll" />
    <ReferenceCopyLocalPaths Include="$(ProjectDir)\..\Libraries\rlottie\$(Platform)\RLottie.pri" />
    <!--<ReferenceCopyLocalPaths Condition=" '$(Configuration)' == 'Debug' " Include="$(ProjectDir)\..\Libraries\rlottie\$(Platform)\zlib1.dll" />-->
  </ItemGroup>
</Project>